### ISSUE TITLE
Add more logs for timestamp validation

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#1004]
### Is your feature request related to a problem?

When using the `notation verify` command to validate a signature with timestamp validation enabled, the signature verification succeeds even if the signing certificate has expired, provided the signature was generated before the certificate’s expiry. This behavior is expected. However, the verbose log output is not informative, as shown below:

```
INFO Performing timestamp verification...
INFO TSA identity is: ***
Successfully verified signature for ***
```

### What solution do you propose?

The current log indicates that timestamp validation is enabled and is now validating the timestamp:

```
INFO Performing timestamp verification...
```

Subsequently, the log shows the TSA identity:

```
INFO TSA identity is: ***
```

It is proposed to enhance the log output to provide more detailed information about the timestamp verification process. For example, the log should indicate whether each certificate in the certificate chain has expired or not.

Examples for valid certificates:

```
INFO Performing timestamp verification...
INFO The certificate <Subject of Leaf> is still valid and will expire on <Time>.
INFO The certificate <Subject of Intermediate> is still valid and will expire on <Time>.
INFO The certificate <Subject of Root> is still valid and will expire on <Time>.
```

Examples for an expired leaf certificate:

```
INFO Performing timestamp verification...
WARN The certificate <Subject of Leaf> has expired. It expired on <Time>.
INFO The certificate <Subject of Intermediate> is still valid and will expire on <Time>.
INFO The certificate <Subject of Root> is still valid and will expire on <Time>.
```

Additionally, we can make it more clear about what TSA identity is

```
INFO The subject of TSA leaf/signing certificate is: ***
```

### What alternatives have you considered?

There could be other information printed out for timestamp validation. Any suggestions are welcome.

### Any additional context?

Notation v1.2.0-beta.1

**Comment by Two-Hearts** [comment]
Closing as completed.
