### ISSUE TITLE
Release notation-v0.7.0-alpha.1

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#104]
Proposing we release notation-v0.7.0-alpha.1 as we have completed the milestone. Release process is defined here.

High level deliverables as as follows:

- [x] Decide on main commit for a release 
- [ ]  Cut branch named v0.7.0-alpha.1 based on agreed upon main commit
- [x] Cut a tag named v0.7.0-alpha.1
- [x] Update README.md

/cc @SteveLasker @NiazFK  @justincormack @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by sajayantony** [comment]
+1
