### ISSUE TITLE
Add support for image-indexes

### ISSUE THREAD

**Issue by roeishuster** [notaryproject/notation#1080]
### Is your feature request related to a problem?

Currently, we cannot sign image indexes, and we use image indexes in some scenarios.
Without singing them, we can't fully run notation with ratify as we cannot validate this kind of artifact.

### What solution do you propose?

To be able to sign image-indexes too, same as regular images.

### What alternatives have you considered?

Excluding specific pods/namespaces that use image indexes or forcing the use of images only in our environment which is not good enough.

**Comment by FeynmanZhou** [comment]
Hi @roeishuster , do you expect to sign both the image index and its child image manifest or sign the image index only? Is it a scenario of signing and verifying multi-arch image? It would be good to elaborate more on your feature request. Thanks

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/9e4a0aae-6786-44c6-aac9-277351359555">

**Comment by roeishuster** [comment]
@FeynmanZhou What we see in our pods verification is the image index only, so we think it would be sufficient to be able to sign the index only.

**Comment by FeynmanZhou** [comment]
Hi @roeishuster , notation should be able to sign the image index only. Have you ever signed it before verifying with Ratify? Is there any specific errors?

**Comment by roeishuster** [comment]
@FeynmanZhou it looks like you are right, we can close this :)
