### ISSUE TITLE
[Feature] Support identity token when fetching registry access token

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation#125]
When fetching the bearer token (registry access token), `notation` assumes the auth to the `realm` is basic auth.
However, it could also be a bearer auth.

To present the identity token with bearer auth instead of the basic auth, the users should leave `--username` blank and put the identity token in the `--password`.
```bash
unset NOTATION_USERNAME
export NOTATION_PASSWORD=$token
```

**Comment by shizhMSFT** [comment]
According to [Docker Registry v2 authentication](https://docs.docker.com/registry/spec/auth/token/#requesting-a-token), identity token support requries OAuth2 support.

**Comment by SteveLasker** [comment]
@shizhMSFT, is this a short term, or long term fix? Is this something we can unify, where the NOTATION_USERNAME can be set to 0000-000 or something similar to other patterns?
Will this be incorporated into a `notation login`, or an underlying auth provider similar to the `docker login` model?

**Comment by shizhMSFT** [comment]
@SteveLasker This issue will be on hold until we migrate to [oras-go](https://github.com/oras-project/oras-go).

**Comment by SteveLasker** [comment]
ok, so this is a short-term fix, that makes sense. 
From a docs/examples perspective, it would far easier to always have the two variables defined. Can we just update the proposal to use either "" for NOTATION_USERNAME or the 000-000 pattern when using tokens?

**Comment by shizhMSFT** [comment]
Empty string sounds better.
```bash
export NOTATION_USERNAME=""
export NOTATION_PASSWORD=$token
```
