### ISSUE TITLE
Release notation-v0.7.1-alpha.1

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation#127]
Since notation `v0.7.0-alpha.1`, we found many bugs and fixed them in the `main` branch.

It is the time to release a patched release `v0.7.1-alpha.1`.

**Comment by shizhMSFT** [comment]
@SteveLasker could you 👀?

**Comment by SteveLasker** [comment]
seems good to me. @iamsamirzon ?

**Comment by iamsamirzon** [comment]
where can I see the list of fixed issues? Also is this backwards compatible ?

**Comment by shizhMSFT** [comment]
@iamsamirzon They are all in the commit history (see https://github.com/notaryproject/notation/compare/v0.7.0-alpha.1...main).

**Comment by shizhMSFT** [comment]
> Also is this backwards compatible ?

Yes, there is no breaking change. That's why it is just a PATCH version update.

**Comment by iamsamirzon** [comment]
Thanks @shizhMSFT . I am good with this.
