### ISSUE TITLE
Update artifact spec dependency

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation#132]
A security patch was patched to [oras-project/artifacts-spec v1.0.0-draft.1](https://github.com/oras-project/artifacts-spec/tree/v1.0.0-draft.1). `notation` needs to be update as well to reflect the patch.

**Comment by sajayantony** [comment]
Should we tag artifacts spec with a new patch tag or update the existing one. What is the common practice here?

**Comment by shizhMSFT** [comment]
I think a new patch tag would be better. Since `notation` does not show the git commit sha in `notation -v`, it is hard to identify if a binary has been patched or not if it uses the same version number.

**Comment by sajayantony** [comment]
Can you please open an issue and recommend the tag needed?

**Comment by shizhMSFT** [comment]
Opened an issue https://github.com/oras-project/artifacts-spec/issues/79.

Before a new release tag for `artifacts-spec` coming out, `notation` will continue reference by `artifacts-spec` commit sha.

**Comment by shizhMSFT** [comment]
[oras-project/artifacts-spec](https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-draft.1.1) has released a new version `v1.0.0-draft.1.1` with the security update.

I will update #133 to reflect the update.
