### ISSUE TITLE
support "attach"ing signatures generated by a separate crypto mechanism

### ISSUE THREAD

**Issue by rchincha** [notaryproject/notation#151]
The use case is as follows:
1. Signing service - signs images (private keys protected)
2. Release service - releases/pushes signed images
3. Verification service - verifies images

There is strict separation between these roles

In this case, what cosign does is ideal [1]. 

References:
[1] https://github.com/sigstore/cosign/blob/main/EXAMPLES.md#sign-with-openssl-verify-with-cosign

**Comment by rchincha** [comment]
Current model is,
1. Push an image
2. Discover/fetch image and sign
3. Push signature

In our model,
1. Get image signed
2. Push image
3. Push signature

**Comment by gokarnm** [comment]
@rchincha , maybe I'm missing something here. In the cosign [example](https://github.com/sigstore/cosign/blob/main/EXAMPLES.md#sign-with-openssl-verify-with-cosign)  

1. The image is present in a registry (already pushed)
2. cosign generates a payload to be signed from the image in registry
3. Sign the payload with openssl
4. Push the signature to registry using cosign

This seems similar to the sequence in Notation currently. Can you clarify on the ask, a description of how you the user experience to be using Notation will help.

**Comment by rchincha** [comment]
3. Sign the payload with openssl

^ for us really an OPAQUE_FUNC(payload.json) -> payload.sig

So, can notation now combine payload.sig + payload.json (image manifest) and push to the registry in one or more steps.

**Comment by gokarnm** [comment]
Got it. Notation will provide an [extensibility mechanism](https://github.com/notaryproject/notaryproject/pull/124) to plugin into existing crypto mechanisms. Users and vendors can implement plugins to support integration with their own crypto systems. E.g. One can implement an OpenSSL plugin for Notation that will allow you to sign and push once you have installed and configured the plugin.

Preliminary example based on the spec

`notation key add --name "mysigningkey" --id "keyid" --plugin "com.openssl.nv2plugin"`
`notation sign $IMAGE --key mysigningkey`

**Comment by rchincha** [comment]
Not quite. Would more like the following.

oras/notation: get image bits for $IMAGE to be signed (say the manifest) -> <sig>
...
notation push $IMAGE --signature <sig>
^ this still does the artifact push.

Of course, notation can mandate some secure well-known signature schemes such as rsa2k-sha256 etc.

**Comment by rchincha** [comment]
In agreement with overall problem statement.

About the implementation, just note that the pipeline stage wherever images are signed and signatures produced may not want to use notation directly. That said, in your example scenario, that "external executable" could just make a remote API call and get the signature and put it in a place notation can then proceed to pick up and package. Would leave it to you if you want to define a contract for this process (which the external executable needs to follow) or just define a cmdline arg (like cosign does).

**Comment by gokarnm** [comment]
Glad to be on the same page! We have a [PR](https://github.com/notaryproject/notaryproject/pull/124/files) for the contract the external executable needs to follow. Here are details about the [installation and protocol](https://github.com/notaryproject/notaryproject/pull/124/files#diff-3ad0d4bca93e75a8cdf8d94a4173d43d5d896320d00c52622244376c4779dab6R24) used by plugins, and here is a contract for [signature generator](https://github.com/notaryproject/notaryproject/pull/124/files#diff-3ad0d4bca93e75a8cdf8d94a4173d43d5d896320d00c52622244376c4779dab6R93). Feel free to provide feedback.

I see benefits in the command line arg approach, where the control is inverted, I'll include that in a subsequent revision of this spec, and ping you if you want to review it for your use case.

**Comment by gokarnm** [comment]
The plugin protocol uses standard streams, Notation will call plugin executable, passes a json request using stdin, and expects a json response in stdout. Protocol and contracts are defined [here](https://github.com/notaryproject/notaryproject/pull/124/files#diff-3ad0d4bca93e75a8cdf8d94a4173d43d5d896320d00c52622244376c4779dab6R48).

**Comment by rchincha** [comment]
@dtzar, @gokarnm sounds like a `openssl` wrapper is needed to comply wit the plugin contract. If you were to write one (or we do), where would that land? Since it is likely to be the most generic one, can it be maintained in `notation` project itself?

**Comment by dtzar** [comment]
related to https://github.com/notaryproject/notation-go/issues/14

**Comment by rchincha** [comment]
@dtzar is there test code or a working implementation which demonstrates this signature generation offload mode?

**Comment by dtzar** [comment]
No, this is currently planned for the future.
https://github.com/notaryproject/roadmap/issues/42

**Comment by rchincha** [comment]
If all action items are tracked, not sure how much more useful this issue can be. Pls close.

**Comment by hallyn** [comment]
Yeah issue #42 seems to cover it, thanks.
