### ISSUE TITLE
add support for binary-encoded x509 certs

### ISSUE THREAD

**Issue by sozercan** [notaryproject/notation#157]
`notation verify` only supports validating with ASCII-encoded x509 certs (PEM)

Today, you can convert a binary encoded DER to PEM and verify using PEMs:
`openssl x509 -in mycert.crt -inform DER -out mycert.pem`

However, users shouldn't need to do this conversion manually and notation should add support for binary-encoded x509 certs

**Comment by SteveLasker** [comment]
Tagging @qmuntal to see if you can pick this up. Our favorite issue hunter...

**Comment by patrickzheng200** [comment]
Taking a look.

**Comment by dtzar** [comment]
This is complete via the linked PR 235

**Comment by dtzar** [comment]
Realized now that this issue is not done.  The PR got closed without merging.

**Comment by patrickzheng200** [comment]
@dtzar FYI, the file related in PR [235](https://github.com/notaryproject/notation/pull/235/files) is no longer there (therefore, I closed that PR without merging). Instead, we are supporting verify with binary encoded DER [here](https://github.com/notaryproject/notation-core-go/blob/1d963fd57141fedb192a064867fb3114e43220cb/x509/cert.go#L24).

**Comment by dtzar** [comment]
@patrickzheng200 - has this been tested/supported with the latest build of `notation verify`?

**Comment by patrickzheng200** [comment]
> @patrickzheng200 - has this been tested/supported with the latest build of `notation verify`?

@dtzar Yes, I did an end-to-end test on this: sign and push an image to ACR then remotely verify it using `notation verify` with a DER certificate. Both cache hit and cache miss scenarios are covered.
