### ISSUE TITLE
Notation design goals

### ISSUE THREAD

**Issue by gokarnm** [notaryproject/notation#161]
### Discussed in https://github.com/notaryproject/notation/discussions/160

- [x] create new repo
- [x] rename repo

<div type='discussions-op-text'>

<sup>Originally posted by **gokarnm** April 18, 2022</sup>
# Notation and notation-go-lib design goals

### Goals

* An integrator should be able to reuse most of the implementation of Notary v2 specs from the lib, without being required to use the CLI
    * At a high level this includes registry authentication, interaction with registry including ORAS APIs, key config, trust store and trust policy, plugin model, Notary V2 signature envelope
* An integrator should be able to generate basic Notary V2 signatures without dependency on other features, like Notation key configuration
* An integrator should be able to verify basic Notary V2 signatures using their own verification policies, without reliance on Notation defined trust store and trust policy language.
* Notation should support multiple signature formats without requiring extensive changes to complete implementation
* Notation sign/verify, including remote signing, should be cable of supporting non-registry scenarios

### Proposal

* Split `notation-go-lib` into two part.
    * `notation-core-go` implements 
        * Generation and verification of Notary v2 signature spec using specific signature formats (JWS, COSE). 
        * Signature format agnostic interface and types which can be consumed by higher layers
        * x509 certificate chain validation
    *  `notation-go` 
        *  Has a dependency on `notation-core-go`
        *  Implements registry auth and registry interactions, including ORAS APIs, key config, trust store, trust policy, plugin interaction
*  `notation` CLI will be a thin layer that depends on `notation-go` for most functionality
*  Versioning
    *  Use [semantic versioning](https://semver.org/) for each component `notation-core-go`, `notation-go` and `notation`. Each component revises versions independently.
    *  Every source release contains latest versions of `notation`, `notation-go-lib` and `notation-core`. 
    *  Every binary release only containes `notation`, dependencies are statically linked.</div>

**Comment by sajayantony** [comment]
LGTM!

**Comment by SteveLasker** [comment]
Complete
