### ISSUE TITLE
Release a new version of Notation Client

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#182]
Since notation v0.7.1-alpha.1, we found many bugs and fixed them in the main branch.

It is the time to release a patched release <TBD Version>

https://github.com/notaryproject/notation/issues/119
There are lot of other updates as well.

- [x] Decide on main commit for a release [a80418b](https://github.com/notaryproject/notation/commit/a80418b5b542a470227427f172128dae112b28a4)
- [x]  Cut branch named `v0.9.0-alpha.1` based on agreed upon main commit
- [x] Cut a tag named `v0.9.0-alpha.1`
- [x] Update README.md

**Comment by dtzar** [comment]
I propose v0.9.0-alpha.1 as the version to match the version for notation-go https://github.com/notaryproject/notation-go/issues/48

**Comment by dtzar** [comment]
Remaining PRs which are pretty much ready to go I think we should merge before cut:

- [ ] #181 
- [ ] #180 
- [ ] #179 
- [ ] #178 
- [ ] #177

**Comment by SteveLasker** [comment]
- Holding on #180, as we don't want to break the automated CI, and we're not quite ready to merge https://github.com/notaryproject/notation-core-go/pull/3.

**Comment by SteveLasker** [comment]
@dtzar, would you take the honors to update the readme?

**Comment by dtzar** [comment]
Done. https://github.com/notaryproject/notation/pull/187
