### ISSUE TITLE
Command flags after arguments are discarded without warning 

### ISSUE THREAD

**Issue by qmuntal** [notaryproject/notation#183]
Several folks and I have been hit by this issue:

- `notation sign --key=$KEY_NAME $IMAGE ` works
- `notation sign $IMAGE --key=$KEY_NAME` does not works and errors out with `signing key not found`.

The same problem applies to any non-required flag which is used together with an argument, i.e. `-p/-u`. 

Using flags after arguments seems not to be supported by `urfave/cli`, see https://github.com/urfave/cli/issues/976.

We should at least error early with a meaningful message instead of executing the normal workflow and having a random error message.

@dtzar

**Comment by SteveLasker** [comment]
+1. I realize the positional parameter shouldn’t have named parameters after. 
I like the idea of an error, not even a warning.

**Comment by shizhMSFT** [comment]
Let's move to `github.com/spf13/cobra`.

**Comment by chloeyin** [comment]
> Let's move to `github.com/spf13/cobra`.

I will take a look at it.

**Comment by dtzar** [comment]
Yes, this would be great! It would also help with the user experience because of the autogenerated help and man pages.
