### ISSUE TITLE
Plugin config directory varies based on OS and should be clearer with docs

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#191]
the [os.UserConfigDir()](https://github.com/notaryproject/notation/blob/c61102cdb414a9aa55980bd113496abef3fcf784/pkg/config/path.go#L59) varies and therefore isn't the same based on OS.

i.e. on Ubuntu `~/.config/notation/plugins/azure-kv` works fine.  
on a mac it is `~/Library/Application Support/notation/plugins`

**Comment by dtzar** [comment]
Should be likely updated here: https://github.com/notaryproject/notation/blob/main/specs/notation-config.md

**Comment by FeynmanZhou** [comment]
> Should be likely updated here: https://github.com/notaryproject/notation/blob/main/specs/notation-config.md

@dtzar @yizha1 @notaryproject/notation-release-managers 

To avoid duplicate content maintenance work between the website and the code repo, I will migrate all user guides from this repo to notaryproject.dev including https://github.com/notaryproject/notation/blob/main/specs/notation-config.md.

**Comment by FeynmanZhou** [comment]
@dtzar @yizha1 See https://github.com/notaryproject/notaryproject.dev/pull/80
