### ISSUE TITLE
Create plugin add to place plugin in proper directory

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#193]
Currently `notation plugin` only officially supports the `list` command.  It is confusing, error prone, and time consuming for users to have to go lookup what the proper directory is for plugins.  Suggestion is to add support for `notation plugin add <name> <path-to-local-plugin-file>` which automatically creates the proper directory and adds the plugin file there.

**Comment by sajayantony** [comment]
This might be more challenging for a multi-file plug-in that might be written in Java or .net if the expectation is to copy the plug-in over.

**Comment by dtzar** [comment]
Expectation would be to copy the file over.  It was my understanding that a plugin must be a single executable file - at least that's what I was [reading in the code](https://github.com/notaryproject/notation-go/blob/d75cdbdd5e8b99d38e8d6ef80b5b3b2ec96ad6b5/plugin/manager/manager.go#L142).

**Comment by sajayantony** [comment]
@gokarnm any inputs on this?

**Comment by gokarnm** [comment]
I agree that expecting users to copy over files to appropriate plugin location is error prone and bad CX. This is not prioritized for RC1 by should be by GA release. 
The plugin itself can be a set of files, containing the executable and any dependencies, and is expected to be placed in a sub directory with matching name e.g `~/notation/plugins/com.example.nv2plugin/notation-com.example.nv2plugin`. 

Something like `notation plugin add <name> <path-to-local-plugin-directory>` would work better, and does the following
* Validate that plugin executable exists and has correct permissions as per plugin executable naming convention
* Create directory with <name> in  plugin base directory
* Copy all the file in <path-to-local-plugin-directory> to the plugin sub directory. 

We also have a notion of system and user level paths for [plugin base dir](https://github.com/notaryproject/notation/pull/175/files?short_path=58303a7#diff-58303a7c8433a12658982b5dd8d08ec24d46558e1957994886f966fbf9ff8b20), so probably will need a switch for it and a default value.

**Comment by SteveLasker** [comment]
The multi-file thing is a good issue. Perhaps we can pass in a file, or a directory. This behavior did previously exist, but it was single-file based. 
It's another good first issue for someone to pickup

**Comment by dtzar** [comment]
We should also consider an approach similar to [Docker plugin](https://docs.docker.com/engine/reference/commandline/plugin/).  
i.e. `notation plugin install <name>`

**Comment by Manas23601** [comment]
Can I work on this?

**Comment by yizha1** [comment]
@dtzar Could you confirm it is duplicate of https://github.com/notaryproject/notation/issues/549, which provides more details and context. Maybe we could close this one and track #549

**Comment by dtzar** [comment]
Agree 549 solves the problem and has more detail on a design for implementation
