### ISSUE TITLE
Add unit tests and CodeQL scanning in GitHub CI/CD

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#197]
In order to ensure the high quality of project delivery, I propose to improve the automated testing process for Notary v2. Currently, we need to add some basic e2e tests, unit tests, and integration tests for [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go.](https://github.com/notaryproject/notation-core-go) 

As Notation CLI is used for end-users and it has [multiple packages](https://github.com/notaryproject/notation/releases/tag/v0.9.0-alpha.1) for different platforms (Linux amd64 & arm64 and Windows), it is also recommended to consider the basic usability test cases (e.g. install, build, push, sign, verify) in the automated testing script.

**Comment by dtzar** [comment]
I would like to scope this item to just the E2E testing for notation cli - this will inherently test at least parts of the API "pseudo integration".
notation-go already has unit tests.  
notation-core-go I added https://github.com/notaryproject/notation-core-go/issues/6
Full integration tests should be broken out in a separate work item, but it isn't priority for RC1.

**Comment by FeynmanZhou** [comment]
> I would like to scope this item to just the E2E testing for notation cli - this will inherently test at least parts of the API "pseudo integration". notation-go already has unit tests. notation-core-go I added [notaryproject/notation-core-go#6](https://github.com/notaryproject/notation-core-go/issues/6) Full integration tests should be broken out in a separate work item, but it isn't priority for RC1.

Agree, we could iterate it in the next release.

**Comment by dtzar** [comment]
All of these are merged, so closing out this issue.
