### ISSUE TITLE
Define local credential experience for Registry Authentication

### ISSUE THREAD

**Issue by gokarnm** [notaryproject/notation#206]
Issue to track registry authentication experience in the absence of docker compatible credential provider in #192 . The proposed storage of unencrypted registry credential on local file system allows an attacker to potentially get read/write access to the registry.

Other options to consider, which arguably do not provide better security but gives the responsibility of securing the credentials to the end user, rather than in built support of unencrypted credentials in `notation`.
1. In the absence of a configured credential provider, require the user to provide user name and password as CLI arguments on every command that interacts with the registry (e.g. `notation sign` , `notation verify`)
2. Notation provides a minimal credential provider that takes input from environment variables (one option) as a script, end user can modify the script to pick credentials from file, or any other location they prefer.

I prefer option 1 for RC1, with addition of option 2 post RC1.

@SteveLasker , @sajayantony , @michaelb990 would be great to get your feedback.

Original content from PR #192
---

### Credential File

The credential file is alternative credential store when credential helpers are not available. The default file path is

```
{CONFIG}/notation/auth.json
```

The credential file path can be altered by setting the `credsFile` field of the notation config.

```json
{
    "credsFile": "/absolute/path/to/auth.json"
}
```

Since credentials are stored in plaintext, the permission of the credential file MUST be kept minimum when storing credentials. On Unix / Linux, the permission MUST be either `0600` (default) or `0400` (read-only).

**Comment by gokarnm** [comment]
cc: @iamsamirzon @FeynmanZhou for tracking against appropriate milestone.

**Comment by iamsamirzon** [comment]
Based on discussion in NV2 working group meeting on 6/27, the feedback is to go with the Docker client like experience. User login/password along with docker credential file is for RC-1

**Comment by gokarnm** [comment]
> Based on discussion in NV2 working group meeting on 6/27, the feedback is to go with the Docker client like experience. User login/password along with docker credential file is for RC-1

Correction : User login/password along with docker credential provider support is for RC-1

**Comment by shizhMSFT** [comment]
> > Based on discussion in NV2 working group meeting on 6/27, the feedback is to go with the Docker client like experience. User login/password along with docker credential file is for RC-1
> 
> Correction : User login/password along with docker credential provider support is for RC-1

Elaboration on the above conclusion: Users should use credential store for credentials to registry authentication. If there is no credential store available, users should specify `--username`, `--password` parameters or environment variables to provide credential for each CLI command execution.

**Comment by shizhMSFT** [comment]
> @shizhMSFT - could you point me and @dtzar to the PR where the above elaboration (and implementation) has been done?

The elaboration is just a rewording. Details have been discussed in the NV2 working group meeting on 6/27.

In other words, there is no support for credential file. Since there is no support, we don't need to implement it.

**Comment by shizhMSFT** [comment]
Re-open with #262 for review.

**Comment by dtzar** [comment]
@iamsamirzon - the PR that Shiwei has aligns with what's in the merged PR: https://github.com/notaryproject/notation/pull/218

Also - again I believe we really should close https://github.com/notaryproject/notation/issues/119
