### ISSUE TITLE
notation auth to CNCF ORAS registry

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#211]
### Discussed in https://github.com/notaryproject/notation/discussions/170

<div type='discussions-op-text'>

<sup>Originally posted by **jimmyraywv** May  5, 2022</sup>
I am using the CNCF ORAS registry distribution in k8s. I have setup basic auth with `htpasswd`. The oras CLI can authenticate with the registry using `-u ... -p ...` flags. However, the notation `0.7.1-alpha.1` CLI fails auth with the same `-u ... -p ...` flags. Can someone suggest what I am missing? The command I am using is below:

This succeeds:
```
oras discover -o tree $IMAGE  -u <USERNAME> -p <PASSWORD>
```

This does not succeed:
```
notation sign $IMAGE -u <USERNAME> -p <PASSWORD>
2022/05/04 19:03:32 https://<HOST>:443/v2/<REPO>/manifests/<VERSION>: 401 Unauthorized
```</div>

**Comment by dtzar** [comment]
This was fixed in https://github.com/oras-project/oras-go/releases/tag/v2.0.0-alpha

**Comment by dtzar** [comment]
The [package listed we're currently using ](oras.land/oras-go/v2 v2.0.0-20220620164807-8b2a54608a94) is behind where the fix is at.  Recommend someone upgrades to the latest release https://github.com/oras-project/oras-go/releases/tag/v2.0.0-rc.1 and then we can close this issue out.

**Comment by dtzar** [comment]
@binbin-li since you just updated the login info and I see you listed a TODO on this, assigning to you.  Hopefully quick to complete.

**Comment by binbin-li** [comment]
@dtzar looks like this issue is the same as https://github.com/notaryproject/notation/issues/183, and @chloeyin is fixing it with the PR: https://github.com/notaryproject/notation/pull/255

**Comment by dtzar** [comment]
No @shizhMSFT this has not been resolved by 255.  Look at the go.mod file in main now, it still has a todo and has not been updated.

https://github.com/notaryproject/notation/blob/92807080abba772dc63f64b274b442708f5099c4/go.mod#L15

**Comment by shizhMSFT** [comment]
@dtzar This issue is about UX (i.e. the positions of flags). It is not related to `oras-go` but CLI packages resolved by #255

**Comment by shizhMSFT** [comment]
Removing the `dependency-oras-go` label to reduce confusion.

**Comment by dtzar** [comment]
I see the oras-go dependency was updated in #269
