### ISSUE TITLE
CLI spec for notation inspect

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#213]
**Summary**

CLI spec for notation inspect

**Intended Outcome**
CLI spec is defined for `notation inspect` command and related documents are updated accordingly

**Additional context**

**Comment by priteshbandi** [comment]
Removed from RC2 milestone because its been tracked in https://github.com/notaryproject/notation/issues/172

**Comment by yizha1** [comment]
Close as it was done in RC-2
