### ISSUE TITLE
Implementing verify command 

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#216]
**Summary**

Implementing verify command according to the spec #88 

**Intended Outcome**
`notation verify` command works as defined in the spec

**Additional context**

**Comment by dtzar** [comment]
We need the spec for verify.  [Relevant sign and verify workflow document](https://github.com/notaryproject/notaryproject/blob/main/signing-and-verification-workflow.md).

**Comment by yizha1** [comment]
need more work per verify CLI spec
