### ISSUE TITLE
Implementing Notation directory structure

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#217]
**Summary**

Implementing Notation directory structure according to the spec #167  

**Intended Outcome**

Notation directory structure works as defined by the spec

**Additional context**

**Comment by shizhMSFT** [comment]
Resolved by https://github.com/notaryproject/notation-go/pull/73

**Comment by JeyJeyGao** [comment]
resolved by 
https://github.com/notaryproject/notation-go/pull/104
https://github.com/notaryproject/notation-go/pull/90
