### ISSUE TITLE
Update notation cert add/remove commands for RC1

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#225]
Need to decide what we'll do for RC1, and what we'll do post RC1 to help users easily add and remove certificates for verifications. The assumption is this would transition from the alpha1 config to the RC1 trust stores.

**Comment by iamsamirzon** [comment]
Can we defer the CLI experience for configuring Trust store and Trust policy in a subsequent release. for the first release users can add /remove certificates in the director structure itself.

**Comment by yizha1** [comment]
PR created for Trust store CLI spec https://github.com/notaryproject/notation/pull/361
