### ISSUE TITLE
Update notation key add/remove commands for RC1

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#226]
Need to decide what we'll do for RC1, and what we'll do post RC1 to help users easily add and remove keys for signing. The assumption is this would transition from the alpha1 config to the RC1 trust stores.

**Comment by priteshbandi** [comment]
Already implemented.

* Spec: https://github.com/notaryproject/notation/blob/main/specs/commandline/key.md
* Implementation: https://github.com/notaryproject/notation/blob/main/cmd/notation/key.go
