### ISSUE TITLE
Update notation verify command for RC1

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#228]
Implement the new verify command to use the trust and policy store

- [x] https://github.com/notaryproject/notation/issues/216
- [ ] notation verify spec

**Comment by vaninrao10** [comment]
@yizha1 and @FeynmanZhou - Can you point us to the notation verify CLI command spec ? We believe @iamsamirzon and I that notation verify CLI command is ready but until we verify it against the spec we wont know if we are done.

**Comment by yizha1** [comment]
@vaninrao10 @iamsamirzon There are still CLI spec and verify implementation work. I am now working on "notation sign CLI spec" and "trust store", I will start working on verify CLI spec soon. The implementation of verify is WIP for trust policy and store workflow. The overall status is "In progress"
