### ISSUE TITLE
Update notation list command for RC1

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#229]
- [ ] Spec the CLI command
- [ ] Implement the new list command, deciding the appropriate detailed output

**Comment by iamsamirzon** [comment]
Can the "List" and "Inspect" commands be combined into one?

**Comment by SteveLasker** [comment]
`list` would be the entire list of signatures for an artifact, while `inspect` would be details on a specific signature.

**Comment by priteshbandi** [comment]
Notation supports list command in RC1.
Ref: 
Impl: https://github.com/notaryproject/notation/blob/main/cmd/notation/list.go
Spec: https://github.com/notaryproject/notation/blob/main/specs/commandline/list.md


For inspect command is tracked in seperate issue https://github.com/notaryproject/notation/issues/172
