### ISSUE TITLE
Update notation plugin command for RC1

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#230]
- [ ] Spec the CLI command
- [ ] Implement the new plugin command

NOTE: This may be done as part of the updated plugin work. 
Related to the following other open issues

- [x] https://github.com/notaryproject/notation/issues/193
- [ ] ~~https://github.com/notaryproject/notaryproject/issues/163~~

**Comment by vaninrao10** [comment]
https://github.com/notaryproject/notaryproject/issues/163 -  As discussed in the community meeting "09/15" to be moved to Post RC1.

**Comment by yizha1** [comment]
@SteveLasker Could you confirm whether we can close this issue? We released plugin commands with specs since RC1.

**Comment by yizha1** [comment]
Closed as released in v1.0.0, see document https://notaryproject.dev/docs/user-guides/how-to/plugin-management/
