### ISSUE TITLE
[User Story] - notation inspect - signatures

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#238]
As a user, I want to inspect signatures.

Related item: #172

**Comment by dtzar** [comment]
If the purpose of this command is truly public key discovery, then perhaps `notation inspect` is not the best verb to use.  
One idea:
`notation cert download <base registry or registry/image:sha>`

**Comment by iamsamirzon** [comment]
@dtzar  - I believe this is a duplicate of https://github.com/notaryproject/notation/issues/172

**Comment by dtzar** [comment]
Consolidating to 172, closing this a duplicate.
