### ISSUE TITLE
[User Story] - notation plugin extensibility for sign and verify 

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#240]
As a signer, I want to use an extensible plugin to sign the artifacts
As a verifier, I want to use extensible plugin to verify signed artifacts

- [ ] https://github.com/notaryproject/notation/issues/230

**Comment by yizha1** [comment]
@dtzar @iamsamirzon @vaninrao10 @gokarnm @priteshbandi  I think this user story is done except the plugin CLI, which is tracked by other user stories. And for rc.1, `notation plugin list` will be the only command, I can create a PR to address the `notation plugin list` spec for rc.1

**Comment by yizha1** [comment]
Close as completed.
