### ISSUE TITLE
[User Story] - notation plugin list

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#241]
As a user, I want to list the plugin(s) so that I can view the installed plugin(s)

Implementation items to track:

- [ ] https://github.com/notaryproject/notation/issues/230

**Comment by iamsamirzon** [comment]
This is already supported, for the signature plugin and expected to work for verification plugin. Any bugs can be fixed separately.

**Comment by dtzar** [comment]
I know this already works today and we use this for our notation azure key vault plugin. 

The user story is here to ensure:
1. There is nothing missing/needed for what we're deeming RC-1
2. That we're all on the same page that we want to support this for RC-1

**Comment by priteshbandi** [comment]
Whats the difference between this and https://github.com/notaryproject/notation/issues/240?

**Comment by dtzar** [comment]
@priteshbandi - this is to make sure that **plugin list** works for RC-1.  The other is to make sure that sign and verify works with plugins.

**Comment by JeyJeyGao** [comment]
I will work on this task.

**Comment by yizha1** [comment]
Close as completed.
