### ISSUE TITLE
[User Story] - notation key CRUD

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#242]
As a user, I want to add/update/list/delete keys

Implementation items to track:
- [x] https://github.com/notaryproject/notation/issues/226

**Comment by iamsamirzon** [comment]
@dtzar  - Could you elaborate if you are looking to  do CRUD operation on keys stored locally or remotely? If remotely, are we just doing CRUD on the remote key identities/aliases ?

**Comment by iamsamirzon** [comment]
This is already implemented for Plugins to specify the signing keys in signingkeys.json

**Comment by dtzar** [comment]
We'd like to support for RC-1 what is covered in [this article](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push).  Effectively - yes this is a remote key reference via plugin.  Notation + plugin today already supports CRUD, but adding here to make sure we're all on the same page for RC-1 support and also in case there is anything else we might be missing which needs to be updated.

**Comment by yizha1** [comment]
Close it as it is complete.
