### ISSUE TITLE
[User Story] - notation cert CRUD

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#243]
As a user, I want to add/list/update/delete (CRUD) certificates.

Implementation items to complete story:

- [x] https://github.com/notaryproject/notation/issues/225
- [x] https://github.com/notaryproject/notaryproject/issues/144

**Comment by yizha1** [comment]
How about command `notation cert generate-test`, which generates a test RSA key and a corresponding self-signed certificate? With this command, user can easily try notation sign & verify for testing purpose, see example showed in this document https://github.com/notaryproject/notation/blob/main/docs/hello-signing.md

**Comment by yizha1** [comment]
This issue is part of #38

**Comment by priteshbandi** [comment]
This has been already implemented in RC1.
