### ISSUE TITLE
Implement notation CLI weekly dev build

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#275]
**Summary**
Implement notation CLI weekly dev build, which was discussed in https://github.com/notaryproject/notation/discussions/261

**Acceptance Criteria**

- Notation CLI dev build is triggered automatically every week. 
- The build time should be configurable, by default it is 04:00 PM UTC every Sunday
- The build will include the latest commit that is present on the main branch of notation repo
- No manual changes on go.mod file to update the dependencies, that is to say, use the latest go.mod file on main branch
- The release version for weekly build is `<SemVer>.dev.<YYYYMMDD>`, where SemVer is the last milestone release version, for example v0.9.0-alpha.2.dev.20220730

**Comment by yizha1** [comment]
@JeyJeyGao will you take this issue?

**Comment by JeyJeyGao** [comment]
I will take this issue.
