### ISSUE TITLE
Update Cli spec to reflect username/password options in commands besides login

### ISSUE THREAD

**Issue by binbin-li** [notaryproject/notation#276]
Besides `notation login`, we need `username/password` options in other commands as well since the cli doesn't come with `Credentials Store` configured.

The current cli spec shows only `login` command support `username/password` which needs to be updated accordingly.

**Comment by FeynmanZhou** [comment]
Hi @binbin-li , I assume we need to add `username/password` options to the following commands, right?

- notation sign
- notation verify
- notation push
- notation pull
- notation list

From my perspective, if a user provides credentials for authenticated registry and logs into a registry via `notation login`, is it necessary to do authentication in the other commands above? 

I think Notation should allow other operations by default after `notation login`, which means `username/password` options are only needed for the first-time authentication.

**Comment by binbin-li** [comment]
> Hi @binbin-li , I assume you are requesting to add `username/password` options to the following commands, right?
> 
> * notation sign
> * notation verify
> * notation push
> * notation pull
> * notation list
> 
> If a user provides credentials for authenticated registry and logs into a registry via `notation login`, is it necessary to do authentication in the other commands above?
> 
> I think Notation should allow other operations by default after `notation login`, which means `username/password` options are only needed for the first-time authentication.

@FeynmanZhou from the previous discussions, users can use `username/password` in other commands even though logged in. And the user-typed `username/password` would have higher priority than that from first-time login command.

**Comment by FeynmanZhou** [comment]
> > Hi @binbin-li , I assume you are requesting to add `username/password` options to the following commands, right?
> > 
> > * notation sign
> > * notation verify
> > * notation push
> > * notation pull
> > * notation list
> > 
> > If a user provides credentials for authenticated registry and logs into a registry via `notation login`, is it necessary to do authentication in the other commands above?
> > I think Notation should allow other operations by default after `notation login`, which means `username/password` options are only needed for the first-time authentication.
> 
> @FeynmanZhou from the previous discussions, users can use `username/password` in other commands even though logged in. And the user-typed `username/password` would have higher priority than that from first-time login command.

Got you. The current implementation support specifying `username` & `password` for each command option, we can merge https://github.com/notaryproject/notation/pull/293 to make the spec consistent with implementation in alpha.3. 

From an end user's perspective, I think we should recommend that use `notation login` with specifying `username` & `password`  and provide a doc to instruct users to configure the [Credential Store](https://github.com/notaryproject/notation/blob/main/specs/registry-auth.md#credential-store) at the beginning. 

Going forward, to achieve a simple and secure authentication user experience, I propose to remove `username` & `password` from other options in the next release.

**Comment by priteshbandi** [comment]
Discuss with Yi and probably close it if the work is already done

**Comment by yizha1** [comment]
close it as spec was updated
