### ISSUE TITLE
Bump up golang to `1.19`

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation#277]
[Go 1.19](https://go.dev/blog/go1.19) is released with [release notes](https://go.dev/doc/go1.19)!

It is time to bump up golang version to `1.19` by updating

- `go. mod`
- GitHub Actions

**Comment by dtzar** [comment]
Do you want to have a matrix?  i.e. 1.18/1.19 or just go straight to 1.19 only?

IMO - we should be consistent with what we pick and upgrade them all at the same time.
notation-core-go for instance uses a [matrix of 1.17/1.18](https://github.com/notaryproject/notation-core-go/blob/6670fef9acec555915541f9a394b489c699de3b2/.github/workflows/reusable-build.yml#L11)

**Comment by dtzar** [comment]
Related to https://github.com/notaryproject/notation-go/issues/99

**Comment by shizhMSFT** [comment]
Since `notation` CLI is a binary, we should go straight to `1.19` only.

**Comment by JeyJeyGao** [comment]
I will work on this task.
