### ISSUE TITLE
Remove hardcoded reference to "localhost"

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#279]
Created from #93 to fix hardcoded references to "localhost" to also include 127.0.0.1. Refer one example here. https://github.com/notaryproject/notation/pull/83#discussion_r704681085  .

Desired Resolution
- Address all hardcoded references to "localhost" by doing  a search through all Notation repos.

**Comment by dtzar** [comment]
Doing a search on notation repo, there are only two references:
1. https://github.com/notaryproject/notation/blob/135621679e7781c78471ede28a2e419cd228fb68/cmd/notation/registry.go#L5
2. https://github.com/notaryproject/notation/blob/135621679e7781c78471ede28a2e419cd228fb68/pkg/configutil/docker_config_test.go#L13

2 - is in a test, so likely don't need to replace.

**Comment by shizhMSFT** [comment]
The original comment is to refactor the following code to a function:
https://github.com/notaryproject/notation/blob/4bf25dfacf0239823311e470b702ceb0435a0299/cmd/notation/registry.go#L54

**Comment by priteshbandi** [comment]
Discuss with Yi and probably close it if the work is already done

**Comment by yizha1** [comment]
The problem still exists. Let's address it in rc.2

**Comment by yizha1** [comment]
Only one place in Notation repo: https://github.com/notaryproject/notation/blob/17d3525f5645c9bee69eca6890fccd98780e00eb/cmd/notation/registry.go
