### ISSUE TITLE
Whenever shelling out read both error and std streams for Notation client

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#280]
This issue is created to replace a finding in #93.  Refer example here . https://github.com/notaryproject/notation/pull/83#discussion_r705752817 

Desired Resolution
1. Search through all code in Notation, Notation-go, Notation-go-core and redirect stderr to console.

**Comment by yizha1** [comment]
Errors are already printed to stderr, so suggest closing this issue @iamsamirzon

**Comment by iamsamirzon** [comment]
@priteshbandi  - Could you confirm and close this issue is fixed as expected?

**Comment by priteshbandi** [comment]
Issue is fixed https://github.com/notaryproject/notation-go/blob/8c3ed9217dc8025983f64a5510249a94dc009a86/plugin/plugin.go#L166-L177
