### ISSUE TITLE
Don't overwrite files if file exists unless explicitly indicated by user

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#281]
This issue is created to replace a finding in #93. Refer example here . https://github.com/notaryproject/notation/pull/83#discussion_r705755110 

Desired Resolution

Search through all code in Notation, Notation-go, Notation-go-core and before creating a new file, check for its existence before overwriting it. And unless specifically asked by the user don't overwrite it.

**Comment by shizhMSFT** [comment]
Went through all existing code. Currently, we are not overwriting any files except updating config files.

The original comment was there for docker plugins. However, those plugins have already been removed.

**Comment by shizhMSFT** [comment]
Reopen the issue as `notation sign` has an `--output` option and may overwrite file. However, I think we don't need user confirmation as per common Unix / Linux experience.

**Comment by yizha1** [comment]
Closed, and create new issues for different scenarios if needed.
