### ISSUE TITLE
notation sign/verify to work with local storage

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#283]
Implement notation to work with signatures in the local storage/filesystem.

**Comment by sajayantony** [comment]
Sharing a proposal here - https://hackmd.io/5PmzMOcrSRaCUJzuy_Gbhg 
@gokarnm @toddysm @shizhMSFT

**Comment by toddysm** [comment]
@FeynmanZhou @yizha1 @vaninrao10 is this something we can consider for rc.2?

**Comment by dtzar** [comment]
@toddysm - the bigger user story is set for RC2, but needs more clarity on scope.  Please comment more on this thread which aspect of "local" you desire.

**Comment by yizha1** [comment]
Update the milestone to rc-3 based on the [discussion](https://hackmd.io/WVFhrhvYSFutJpnY6JTDuQ?view#RC-3-Release-Items---March-30th-2023-Can-be-called-GA-----Gives-5-weeks-after-rc-2-release).

**Comment by patrickzheng200** [comment]
Working on this item, design in progress.
