### ISSUE TITLE
Credentials store config is not set up when using notation sign

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#284]
Hi team,

I tried Notation CLI based on the build from the main branch today. But I got the following error:

```
# Generate a self-signed test certificate for testing purposes
$ notation cert generate-test --default "wabbit-networks.io"
generating RSA Key with 2048 bits
generated certificates expiring on 2022-08-09T06:43:14Z
wrote key: /root/.config/notation/localkeys/wabbit-networks.io.key
wrote certificate: /root/.config/notation/localkeys/wabbit-networks.io.crt
wabbit-networks.io: added to the key list
wabbit-networks.io: marked as default

# Sign the image
$ notation sign --plain-http $IMAGE
Error: failed to load config file, error: credentials store config is not set up
2022/08/08 06:43:44 failed to load config file, error: credentials store config is not set up
```

Using `notation --plain-http sign $IMAGE` is also not worked for me.

Is it caused by the [directory structure updates](https://github.com/notaryproject/notation/pull/265)? Any suggestions on this issue?

**Comment by FeynmanZhou** [comment]
cc @shizhMSFT @JeyJeyGao @binbin-li for help

**Comment by JeyJeyGao** [comment]
I will work on this bug fix.

**Comment by FeynmanZhou** [comment]
Thanks @JeyJeyGao for your quick support. Have you found the root cause for this issue?

**Comment by JeyJeyGao** [comment]
According to previous design, credentials store config must exist in notation config.json or docker config.json, but you may not need a credentials store config to sign image for  local registry. To fix the bug, we need to allow empty credentials store config for local reigistry.

**Comment by susanshi** [comment]
@FeynmanZhou , i got the same error , were you able to generate a store config?
