### ISSUE TITLE
Add [Preview] to notation subcommands help

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#305]
Per the [discussion here](https://github.com/notaryproject/notation/discussions/257#discussioncomment-3204893), we should enable a [Preview] or [Experimental] option in the help menu for the root `notation -h` and `notation _subcommand_ -h` which are present, but either not well (or at all) tested but we want to leave in for people to try to utilize. 

This will help set proper expectations with the user experience and also help the development team to properly keep and make prioritization decisions on if coding/testing effort for subcommands should move them out of [Preview] / [Experimental] modes.

**Comment by 1235467Ad** [comment]
Thank You Generous Contributer.

**Comment by dtzar** [comment]
Per community call 11/10, we are going to document which subcommands are "supported" for RC1 in the release notes until we potentially implement this.

**Comment by yizha1** [comment]
Closed as experimental feature is supported, see https://notaryproject.dev/blog/2023/announcing-notation-rc4/#introduce-switch-notation_experimental1-to-enable-experimental-features, and preview mode will not be introduced.
