### ISSUE TITLE
Notation CLI supporting OCI reference type

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#335]
`Notation CLI` depends on `Notation-go` to support OCI reference type. The `Notation-go` work item is tracked here at https://github.com/notaryproject/notation-go/issues/136. Besides the update in `Notation-go`, this issue tracks any other tasks of `notation CLI` to support OCI reference type.

**Comment by iamsamirzon** [comment]
@yizha1  - I think this item and https://github.com/notaryproject/notation-go/issues/136 should both be for RC.1. 

cc: @vaninrao10

**Comment by FeynmanZhou** [comment]
Per today's community call, Notation will migrate to the OCI artifact manifest from the ORAS artifact manifest in RC.1 and the fallback solution is planned in RC.2. 

I am concerned there are still less registries supporting the OCI artifact manifest when RC.1 is available at the end of this month, which means the Notation usability will be broken.
