### ISSUE TITLE
Add version command for notation CLI

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#345]
Currently `notation version` doesn't work, user has to use `--version` to print out the version info, which is limited and generated by CLI framework. 
```
$ notation version
Error: unknown command "version" for "notation"
Run 'notation --help' for usage.
2022/09/21 21:21:41 unknown command "version" for "notation"
$ notation --version
notation version v0.10.0-alpha.3+unreleased
```
`version` command is widely used by many command tools, notation CLI should support `version` command for a stable release. Here is a request to add `notation version ` command, and the following printout is a suggestion for a minimal information to be printed out:
```
Version: 
Go version:
```

**Comment by yizha1** [comment]
Reopen this issue for implementation is not done.

**Comment by yizha1** [comment]
- [ ] spec: https://github.com/notaryproject/notation/pull/376
- [ ] implementation

**Comment by JeyJeyGao** [comment]
I will work on this item.
