### ISSUE TITLE
Auto remove old weekly dev builds

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#369]
Unfortunately, there is no way I could find to filter out the weekly developer builds from the notation repository.  The weekly developer builds are only useful for 2 weeks at the most.  This also makes it hard for someone to find the last full release.  

I propose that the weekly developer build automatically deletes the n-1 or n-2 weekly developer build release and tag so at most there is only one or two developer builds on the release page.

**Comment by yizha1** [comment]
Close it as being stale for more than one year.
