### ISSUE TITLE
Implementation for configure & persist signature envelope format for signing.

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#390]
Implement as per https://github.com/notaryproject/notation/issues/325

**Comment by yizha1** [comment]
- [ ] Implementation in notation-go by https://github.com/notaryproject/notation-go/pull/159
- [ ] Implementation in notation by https://github.com/notaryproject/notation/pull/400

**Comment by yizha1** [comment]
@JeyJeyGao is doing the implementation now

**Comment by priteshbandi** [comment]
Hi Yi - Here we need implementation to adhere by specification because we are yet to define how signature-format flag will work with plugin.

**Comment by yizha1** [comment]
> Hi Yi - Here we need implementation to adhere by specification because we are yet to define how signature-format flag will work with plugin.

I saw you re-opened the spec. I have thought the spec is done because it was closed previously.

**Comment by JeyJeyGao** [comment]
I'm working on this task.
