### ISSUE TITLE
Dead code cleanup and other quality improvements

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#392]
- [ ] Cleanup dead code cleanup in notation-core-go refactoring.
- [ ] [verification/helpers.go#L85: support more types of URI like "domain.com/repository", "domain.com/repository:tag"](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/helpers.go#L85)
- [ ] [verification/verifier.go#L165: verify the plugin's version is equal to or greater than `outcome.SignerInfo.SignedAttributes.VerificationPluginMinVersion`](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/verifier.go#L165)
- [ ] [verification/helpers.go#L147: multi-valued RDNs are not supported; TODO: add spec reference here](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/helpers.go#L147)

**Comment by iamsamirzon** [comment]
@yizha1 , @FeynmanZhou   - The first two items ( dead code clean up and more UTs) should get done as part of refactoring the code for Notation-go and Notation CLI. We believe no changes are required in the notation-core-go repo

The third item, "TODOs", Pritesh will identify the must have TODOs.

cc: @vaninrao10 , @shizhMSFT , @dtzar

**Comment by priteshbandi** [comment]
TODOs identified for RC1
### Refactor:
- [ ] https://github.com/notaryproject/notation/blob/f0e77eb4a55c850e2f49d5a1d457105dc4aa5dde/cmd/notation/list.go#L67
- [ ] https://github.com/notaryproject/notation/blob/193a533eac4741489ee2b43cf2d635015eb3be5e/internal/ioutil/print.go#L62
- [ ] https://github.com/notaryproject/notation/blob/193a533eac4741489ee2b43cf2d635015eb3be5e/internal/ioutil/print.go#L76
- [ ] https://github.com/notaryproject/notation/blob/8d1d4dc77e2b75311db4fd4396b2dfc9e963810c/internal/envelope/envelope.go#L20

### Others:

- [ ] [verification/helpers.go#L85: support more types of URI like "domain.com/repository", "domain.com/repository:tag"](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/helpers.go#L85)
- [ ] [verification/verifier.go#L165: verify the plugin's version is equal to or greater than `outcome.SignerInfo.SignedAttributes.VerificationPluginMinVersion`](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/verifier.go#L165)
- [ ] [verification/helpers.go#L147: multi-valued RDNs are not supported; TODO: add spec reference here](https://github.com/notaryproject/notation-go/blob/75b3248459d677d2a6abcae3dd880775f4456271/verification/helpers.go#L147)

**Comment by yizha1** [comment]
updated milestone to rc.2 per discussion

**Comment by yizha1** [comment]
Close as no activities for more than 6 months. Please open new issues in the respective repo if needed.
