### ISSUE TITLE
Support pagination as default option in notation list CLI.

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#403]
> IMO default behavior should be paginated as ORAS [referrers](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md) API is paginated. Not having pagination will result in an unnecessary load on servers when 1st returned item in the list is what the user wanted. Also, it's usually good practice to have a paginated list API.

Maybe we can create another issue to address your comments. The implementation depends on the behavior of `oras-go` library. IMO, the current spec is good enough for rc.1 release.

_Originally posted by @yizha1 in https://github.com/notaryproject/notation/pull/362#discussion_r991009489_

**Comment by shizhMSFT** [comment]
The [Referrers()](https://pkg.go.dev/oras.land/oras-go/v2@v2.0.0-rc.3.0.20221017083622-5416ed6a6bde/registry/remote#Repository.Referrers) API in `oras-go` is paginated.

**Comment by rgnote** [comment]
Here is the proposal for supporting pagination in `notation list` command

The default experience for this command will be to list ALL the signatures for a given reference. This is the provided behavior in notation rc.1  

After rc.1, `notation list` command will support two new switches

* max-results = <some number>
* next-token = <marker to the next page>

Using these two switches, users will be able to paginate through the entire result set of signatures for a given reference. These two switches are optional. If `--max-results` is not provided, notation will default it to the supported max number by the registry implementation. If `--next-token` is not provided, notation will default to the first page.

Examples:

1. `notation list` - list all signatures
2. `notation list --max-results 10` - list first 10 signatures
3. `notation list --max-results 5 --next-token <token>` - list 5 signatures from the page referring to the given <token>

**Comment by shizhMSFT** [comment]
@rgnote As specified in the [distribution-spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers), the Referrers API does not support listing from the middle of the list. Also, the Referrers API does not support specifying the number of max results to be returned.

**Comment by rgnote** [comment]
@shizhMSFT You are right. I was looking at Oras [spec](https://github.com/oras-project/artifacts-spec/blob/main/manifest-referrers-api.md#paging-results). I will update my comment accordingly.

**Comment by iamsamirzon** [comment]
@rgnote  and @shizhMSFT   will discuss this and then likely move it out of RC-1 into RC-2

cc: @vaninrao10

**Comment by yizha1** [comment]
Confirmed to move this issue out of rc-1 scope. Now moved to "Discuss". We will review all the issues later for rc-2 release scope.

**Comment by yizha1** [comment]
Close this issue as no activities for more than 8 months. Referrers API defined by [distribution spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) supports pagination and Notation has experimental feature `--allow-referrers` that supports it. Please open new issue if you still see any issues.
