### ISSUE TITLE
Address Open SSF scorecard issues

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#408]
Address all high and medium issues found https://github.com/notaryproject/notation/security/code-scanning

- [ ] Create a security policy.  This is a [good template to consider](https://github.com/veraison/go-cose/security/policy).

**Comment by yizha1** [comment]
@dtzar  Can we do it post rc.1?

**Comment by dtzar** [comment]
I would suggest the security policy one, Token Permissions, and Pinned Deps ones be done @ RC-1.  I can't imagine all those things take more than ~1 day of work for one person.  The rest, yes post RC-1.

**Comment by yizha1** [comment]
Most of issues were fixed by PR #730 and #731.

**Comment by yizha1** [comment]
Closed as most issues were fixed. Please create a new issue for new problems.
