### ISSUE TITLE
Threat Modeling for notation (Dir + Config+Registry Interaction)

### ISSUE THREAD

**Issue by vaninrao10** [notaryproject/notation#409]
Threat modeling involves identifying ways that an adversary might try to attack notation and then designing mitigations to prevent, detect or reduce the impact of those attacks.

Aspects:
Dir + Config+Registry Interaction - 1 SDE week
Other Aspect of threat model is tracked under - [https://github.com/notaryproject/notation/issues/391](url)

**Comment by yizha1** [comment]
@vaninrao10 @dtzar I think we can move this issue to pose rc.1?

**Comment by yizha1** [comment]
Confirmed to move this issue out of rc-1 scope. Now moved to "Discuss". We will review all the issues later for rc-2 release scope.

**Comment by yizha1** [comment]
closed as completed, see https://github.com/notaryproject/specifications/blob/main/threatmodels/notation-threatmodel.md
