### ISSUE TITLE
When no key is present, make key add be the default key

### ISSUE THREAD

**Issue by dtzar** [notaryproject/notation#410]
If there are no keys present for notation and you successfully add a key via `notation key add <key>` it does not make this key the default key and hence when you try to sign something it gives this: `Error: signing key not found`

We should add a check that if there are no keys present, we make the key added the default key without having to pass the --default flag.

**Comment by priteshbandi** [comment]
The experience is right but the error message is wrong. Error should say `default signing key not set. Please either set default singing key or specify a key name`.

**Comment by yizha1** [comment]
> The experience is right but the error message is wrong. Error should say `default signing key not set. Please set default singing key or specify a key name`.

Could there be a quick fix for the error message? I am not sure if the error is printed out from CLI or library

**Comment by priteshbandi** [comment]
Yes, posted PR https://github.com/notaryproject/notation/pull/432

**Comment by priteshbandi** [comment]
PR had been merged, closing the issue.
