### ISSUE TITLE
Support expiry duration in days

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#423]
With the current implementation, we yet don't support `d` (e.g. `30d` ).

_Originally posted by @shizhMSFT in https://github.com/notaryproject/notation/pull/417#discussion_r1009073464_
      
`notation sign` command supports an optional `expiry` flag for user to specify a \"best by use\" time for the artifact. The duration can be specified in minutes(m) or/and hours(h). The intention of this issue is to support duration in days, for example, 30d, 1d3h20m.

**Comment by priteshbandi** [comment]
Tracking it in https://github.com/notaryproject/notation/issues/129
