### ISSUE TITLE
define type Errors []error

### ISSUE THREAD

**Issue by patrickzheng200** [notaryproject/notation#426]
In notation certificate command, `errorSlice` is `[]error`. We can define a type `type Errors []error` and implement `func (errs Error) Error string()` to reduce duplicated code. Created this issue to track.

**Comment by Manas23601** [comment]
Please correct me if i'm wrong here. But are you trying to create `type Errors []error` and implement `func (errs Errors) Error string()` instead of `func (errs Error) Error string` ?

**Comment by patrickzheng200** [comment]
Since the recent Go 1.20: https://tip.golang.org/doc/go1.20#errors release already covers this issue, will close it.
