### ISSUE TITLE
Document Typical "Trust Policy" examples that customers may encounter. 

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/notation#438]
For Notation's RC-1 release, lets create a sample of trust policy templates, that customers can use as a reference to build their trust policies.

These examples should be based on real world examples

**Comment by iamsamirzon** [comment]
@toddysm  - Assigning this one to you first. We all can add other examples later.

cc: @vaninrao10

**Comment by yizha1** [comment]
As discussed in the community meeting, closed this issue as the document is available at https://notaryproject.dev/docs/user-guides/tutorials/trust-policy/
