### ISSUE TITLE
GenerateEnvelope plugin request doesnot have expiry.

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#443]
### What is the areas you experience the issue in?

Notation-Core-Go Library

### What is not working as expected?

The generate-envelope plugin request doesnt has access to expiry.

https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md#generate-envelope

```
// Request
{
  "contractVersion" : "<major-version.minor-version>",
  
  // Key id associated with signing key (keyName)
  // in config.json /signingKeys/keys
  "keyId": "<key id>",

  // Optional plugin configuration, map of string-string
  "pluginConfig" : { },

  "payload" : "<Base64 encoded payload to be signed>",
  
  // The type of payload - currently a descriptor
  "payloadType" : "application/vnd.cncf.notary.payload.v1+json",
  
  // The expected response signature envelope
  "signatureEnvelopeType" : "application/jose+json"
}
```

### What did you expect to happen?

the generate-envelope plugin request should have access to expiry

### How can we reproduce it?

NA

### Describe your environment

NA

### What is the version of your Notation CLI or Notation Library?

NA

**Comment by yizha1** [comment]
Per community discussion:

- [ ] Update plugin spec
- [ ] Notation Implemention
- [ ] Notation plugin Implemention

**Comment by yizha1** [comment]
Closed as all PRs merged
