### ISSUE TITLE
Deadcode cleanup improvement Notation

### ISSUE THREAD

**Issue by vaninrao10** [notaryproject/notation#446]
Shiwei's Team

- [x] [notation/cmd/notation/list.go](https://github.com/notaryproject/notation/blob/f0e77eb4a55c850e2f49d5a1d457105dc4aa5dde/cmd/notation/list.go#L67)
Line 67 in [f0e77eb](https://github.com/notaryproject/notation/commit/f0e77eb4a55c850e2f49d5a1d457105dc4aa5dde)
 // TODO: this is a temporary function and will be replaced after 

- [x] [notation/internal/ioutil/print.go](https://github.com/notaryproject/notation/blob/193a533eac4741489ee2b43cf2d635015eb3be5e/internal/ioutil/print.go#L62)
Line 62 in [193a533](https://github.com/notaryproject/notation/commit/193a533eac4741489ee2b43cf2d635015eb3be5e)
 // TODO[https://github.com/notaryproject/notation/issues/304]: print out failed validations as warnings. 

- [x] [notation/internal/ioutil/print.go](https://github.com/notaryproject/notation/blob/193a533eac4741489ee2b43cf2d635015eb3be5e/internal/ioutil/print.go#L76)
Line 76 in [193a533](https://github.com/notaryproject/notation/commit/193a533eac4741489ee2b43cf2d635015eb3be5e)
 // TODO[https://github.com/notaryproject/notation/issues/304]: print out detailed errors in debug mode. 

- [ ] [notation/internal/envelope/envelope.go](https://github.com/notaryproject/notation/blob/8d1d4dc77e2b75311db4fd4396b2dfc9e963810c/internal/envelope/envelope.go#L20)
Line 20 in [8d1d4dc](https://github.com/notaryproject/notation/commit/8d1d4dc77e2b75311db4fd4396b2dfc9e963810c)
 // TODO: abandon this fature in RC1. 

- [x] Cleanup dead code in notation-go and notation; should be part of ongoing refactoring.
- [x] Add more UTs wherever required for notation-go

**Comment by yizha1** [comment]
update milestone to rc.2 per discussion.
