### ISSUE TITLE
Expiry doesn't support `day`.

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#451]
Currently `day` is not support yet.

_Originally posted by @yizha1 in https://github.com/notaryproject/notation/pull/439#discussion_r1027584159_

**Comment by yizha1** [comment]
@priteshbandi There was an existing issue I created for tracking it. https://github.com/notaryproject/notation/issues/423

**Comment by priteshbandi** [comment]
Duplicate of https://github.com/notaryproject/notation/issues/423
