### ISSUE TITLE
Failed to verify a signature using the build from the main branch

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#463]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

Failed to verify a signature using the build from the main branch:
```
$ notation list localhost:5000/net-monitor:v1
localhost:5000/net-monitor@sha256:4fa86cb3ba7764942c173f6705390b2c340c5356132614e51996c49505c3ebad
└── application/vnd.cncf.notary.v2.signature
    └── sha256:956170bb73738151ecbca03c800f17ac2443f4b1b86b78b25edf068c4efa50bd

$ notation verify localhost:5000/net-monitor@sha256:4fa86cb3ba7764942c173f6705390b2c340c5356132614e51996c49505c3ebad
Signature verification failed for all the signatures associated with digest: sha256:4fa86cb3ba7764942c173f6705390b2c340c5356132614e51996c49505c3ebad
Error: signature verification failed
```

### What did you expect to happen?

Can be verified successfully using `notation verify`.

### How can we reproduce it?

Follow the quick start https://notaryproject.dev/docs/quickstart/ to sign and verify a container image

### Describe your environment

Ubuntu 20.03

### What is the version of your Notation CLI or Notation Library?

Build from the main branch on Dec 3:
Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     v0.12.0-beta.1+unreleased
Go version:  go1.19
Git commit:  55e8b5b3554299d379f98d77931f3a385de67bf7

**Comment by yizha1** [comment]
@FeynmanZhou Is this problem still there?

**Comment by patrickzheng200** [comment]
Closing this issue as our RC.1 release have fixed it.
