### ISSUE TITLE
Release v1.0.0-rc.1 for notation CLI

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#470]
Release `v1.0.0-rc.1` for `notation CLI`:

- [x] Update dependency to use `notation-core-go` version `v1.0.0-rc.1` 
- [x] Update dependency to use `notation-go` version `v1.0.0-rc.1`
- [x] Decide on main commit for a release
- [x] Cut branch named `v1.0.0-rc.1` based on agreed upon main commit
- [x] Cut a tag named `v1.0.0-rc.1`

@SteveLasker @NiazFK Please respond with `+1` comment for approval.

cc: @iamsamirzon @vaninrao10 @priteshbandi @toddysm @FeynmanZhou @shizhMSFT

**Comment by SteveLasker** [comment]
+1

**Comment by NiazFK** [comment]
+1

**Comment by yizha1** [comment]
Closed as rc.1 has been released
