### ISSUE TITLE
Implement `notation logout -all`

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#489]
Implement `notation logout -all`

_Originally posted by @priteshbandi in https://github.com/notaryproject/notation/pull/484#discussion_r1052912177_

**Comment by yizha1** [comment]
@priteshbandi Is this issue still applicable?

**Comment by yizha1** [comment]
As discussed during community meeting, closed this issue and we can create a new issue later on once the scenario is clear.
