### ISSUE TITLE
Documentation/Spec]Update sign and verify command spec to add --debug and --verbose flags

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#491]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

NA

### What did you expect to happen?

NA

### How can we reproduce it?

NA

### Describe your environment

-

### What is the version of your Notation CLI or Notation Library?

-

**Comment by yizha1** [comment]
@priteshbandi could you check whether this issue can be closed
