### ISSUE TITLE
Support Azure KeyVault for EV CodeSigning keys

### ISSUE THREAD

**Issue by gillg** [notaryproject/notation#492]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

Using a "local" key could be considered unsecure most of the time because there is a risk of disclosure.
Moreover, to get an EV CodeSigning cert some requirements are to make the private key completely unknown and managed by an HSM device compatible FIPS 140-2 level 2.

The cloud service Azure KeyVault meets these requirements and is very convinient to sign files in flexible ways.

### What solution do you propose?

In this case the user needs to provide new args to the cli : 
`--azure-key-vault-url` (could be targeted to a generic `--keystore` arg)
`--azure-key-vault-certificate` (could be targeted to a generic `--alias` arg)
`--azure-key-vault-accesstoken` (could be targeted to a generic `--password` arg)  this parameter is mandatory for autentication. The user already has one or can generate it on the fly with `az account get-access-token --resource "https://vault.azure.net" --tenant $tenantID` for example.

Optional args for auth :
These 3 args can be used to call the similar call `az account get-access-token ....` through the SDK. `--azure-key-vault-accesstoken` can be ignored in this case.
```
--azure-key-vault-client-id
--azure-key-vault-client-secret
--azure-key-vault-tenant-id
```

To attach the cert to the image you just need to use : https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificate/getcertificate
Get the cert also allows to get its associated "key-id" and "key-version" used to call the sign method.

The API method https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign wait for a body like 
`{"alg":"RS256","body":"data-digest-to-sign"}` and return the signature in base64.
The alg can be one of https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign#jsonwebkeysignaturealgorithm

### What alternatives have you considered?

It's not possible to retrieve the private key in case of EV Cert, so no solution.

### Any additional context?

Other implementable interesting keystores :
* PKCS#12, JKS and JCEKS files
* PKCS#11 hardware tokens ([YubiKey](https://www.yubico.com/), [Nitrokey](https://www.nitrokey.com/), etc)
* Cloud key management systems ([AWS KMS](https://aws.amazon.com/kms/), [DigiCert ONE](https://one.digicert.com/), [Google Cloud KMS](https://cloud.google.com/security-key-management), [SSL.com eSigner](https://www.ssl.com/esigner/))

**Comment by FeynmanZhou** [comment]
Hi @gillg ,

Thanks for your feature request. Did you notice that Notation has an [Azure Key Vault plugin](https://github.com/Azure/notation-azure-kv)? You can check out [this guide](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push) for details. 

Please let us know if this AKV plugin solution meets your needs or not. Thanks

**Comment by gillg** [comment]
Thanks @FeynmanZhou ! I missed it !
So the plugin seems not really usable in the current state but I created a issue on their side.

https://github.com/Azure/notation-azure-kv/issues/54

**Comment by yizha1** [comment]
Closed as this is tracked at https://github.com/Azure/notation-azure-kv/issues/54
