### ISSUE TITLE
Notation Verify should warnings output to Stderr

### ISSUE THREAD

**Issue by byronchien** [notaryproject/notation#513]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

notation outputs warnings in some cases (such as when tag references are resolved), and these warnings are written to stdout.

### What did you expect to happen?

I expect any warnings to be written to stderr instead of stdout.

### How can we reproduce it?

Can reproduce this behavior by running notation sign or verify with a tag reference, ex: `notation verify localhost:5000/net-monitor:v1`

### Describe your environment

go version 1.19.2, darwin/amd64

### What is the version of your Notation CLI or Notation Library?

v1.0.0-rc.1+unreleased

**Comment by mintbomb27** [comment]
@byronchien I think this is resolved in #497
