### ISSUE TITLE
Proposal to update the CODEOWNERS file and add MAINTAINERS file

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#514]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

The current content of the CODEOWERS file does not list the actual owners and points to a Team on GitHub. This does not provide enough visibility who the owners are.

### What solution do you propose?

The proposal is to create a seed list of maintainers for each repository (aka considered sub-project) under the Notary Project organization and update the CODEOWNERS and MAINTAINERS files for each repository with that list. As per the current [governance document](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md):
> Potential new maintainers should be ongoing active participants in the project

Hence, I propose that repo maintainers are proposed from the list of currently active participants in the Notary community by selecting them from the list of [code contributors](https://github.com/notaryproject/notation/graphs/contributors) for the last 3-6 months or meeting participants as per the [meeting notes](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw).

I also propose to nominate individual maintainers in separate issues and put for a vote by the active participants' community. 

### What alternatives have you considered?

None

**Comment by SteveLasker** [comment]
👍

**Comment by toddysm** [comment]
@lachie83 Started a PR #515 - let's use as example for submission. The goal is to have two files:

CODEOWNERS file that has the GitHub handle of the maintainer - this is used for automation like PR reviews
MAINTAINERS file that has the Full Name, email, and GitHub handle - this one is used for visibility and transparency

**Comment by FeynmanZhou** [comment]
@toddysm It seems the [governance document](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md) doesn't clarify the specific requirements or criteria for nominating a new maintainer. 

Do you think we should clarify it by including some basic requirements, such as authoring at least x substantial PRs merged to the repository/subproject? See [Kubernetes community membership](https://github.com/kubernetes/community/blob/master/community-membership.md#community-membership) as an example.

**Comment by toddysm** [comment]
@FeynmanZhou thanks for the note. Tagging @lachie83 FYI.

Let's file a new issue with a proposal for an update to the governance. Having a [CONTRUBUTOR LADDER](https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md) would be a good approach.

**Comment by lachie83** [comment]
Thanks @FeynmanZhou. I think we could add a maintainer requirements and that would be helpful moving forward. 

I think in this instance, we are codifying a set of seed maintainers based on activity and general agreement across the current contributor base. The way the current governance reads, in absence of subrepo specific maintainers, org maintainers fulfill the role.

**Comment by yizha1** [comment]
Closed as corresponding PR were merged.
