### ISSUE TITLE
Update the branch policies for the repository

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#519]
### What is the areas you would like to add the new feature to?

Note: @SteveLasker changed the branch policies to checkmarks to indicate the current status

Notation CLI

### Is your feature request related to a problem?

After reviewing the branch policies for the repository, it seems that the `main` and release branches can benefit with more strict push and PR review policies. 

### What solution do you propose?

I would like to propose updating those as follows:

- Follow naming convention `release/<release-number>` for release branches. Example `release/rc.1`
- Use the following rules for `main` and `release/*` branches:
    - Require PR before merging
      - [x] Require 3 approvals
      - [x] Dismiss stale PR approvals when new commits are pushed
      - [x] Require review from Code Owners
      - [x] Require status checks to pass before merging
      - [x] Require conversation resolution before merging
      - [x] Require signed commits
      - [x] Do not allow bypass the above settings

Please add your comments and proposals for additional changes to this issue.

### What alternatives have you considered?

N/A

**Comment by yizha1** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by SteveLasker** [comment]
Several of the rules were already created on `main`, but not captured.
I've updated the list to checkboxes, updating which were completed prior and now.
Note, signed commits was added, however DCO is also enabled on this repo.

**Comment by vaninrao10** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by priteshbandi** [comment]
LGTM but IANAM

**Comment by yizha1** [comment]
Closed as all the rules were applied.
