### ISSUE TITLE
Simplify signing experience

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#537]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

Currently, user need to perform some per-requisites like adding key before they can start signing, which is not the best CX.
Signing steps are
1. Add Key `notation key add --plugin ${plugin} --id ${keyId} ${keyName}`
2. Sign `notation sign -k ${keyName}`

### What solution do you propose?

Notation can accept `plugin` and `id` flag in `sign` command so that user wont need to add key for signing (if they dont want to save it) and they can directly call
```shell
notation sign --plugin ${plugin} --id ${keyId}
```

### What alternatives have you considered?

N/A

### Any additional context?

N/A

**Comment by mintbomb27** [comment]
I was thinking of trying to implement this. I took a look at the code, and I think one approach to do this is to modify the [`GetSigner()`](https://github.com/notaryproject/notation/blob/c47a4522c490f4b1cdcadeb0abd9307b63952394/internal/cmd/signer.go#L15) to create a signer there using `NewFromPlugin()`, by taking the id, plugin name, and configs from the `opts`, and returning that.

I'm new to notation, and would like some help here. Is there any other method to go about this, or should I make any change to my method? Do let me know. @priteshbandi @yizha1

**Comment by iamsamirzon** [comment]
+1 Good idea.

**Comment by priteshbandi** [comment]
@mintbomb27 I've raised a PR https://github.com/notaryproject/notation/pull/553 to update the spec for supporting this scenario. If community agrees then we can merge my PR and then you can work on implementation.

**Comment by priteshbandi** [comment]
Fixed in https://github.com/notaryproject/notation/pull/579
