### ISSUE TITLE
Not able to build Notation project from source

### ISSUE THREAD

**Issue by Manas23601** [notaryproject/notation#562]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

After following the [instructions](https://github.com/Manas23601/notation/blob/main/building.md) to install notary from source. I'm unable to view the new changes while running `docker --help`. 

### What did you expect to happen?

I'm failing to see the following in `docker --help`

```
Management Commands:
  generate*   Generate artifacts (CNCF Notary Project, 0.1.0)
  notation*   Manage signatures on Docker images (CNCF Notary Project, 0.5.3-alpha)

```

### How can we reproduce it?

Follow the instructions to build from source

### Describe your environment

Installation method:Git
OS:  Ubuntu 22.04
Shell: bash
Golang Version : 20.1

### What is the version of your Notation CLI or Notation Library?

```
Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     v1.0.0-rc.1+unreleased
Go version:  go1.20
Git commit:  f463f0cb16753d5e398b3bb2d6e26a0e23e519c7
```

go.mod file
```
module github.com/notaryproject/notation

go 1.19

require (
	github.com/docker/docker-credential-helpers v0.7.0
	github.com/notaryproject/notation-core-go v1.0.0-rc.1
	github.com/notaryproject/notation-go v1.0.0-rc.1.0.20230203031935-510def1a3f48
	github.com/opencontainers/go-digest v1.0.0
	github.com/opencontainers/image-spec v1.1.0-rc2
	github.com/sirupsen/logrus v1.9.0
	github.com/spf13/cobra v1.6.1
	github.com/spf13/pflag v1.0.5
	oras.land/oras-go/v2 v2.0.0
)

require (
	github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358 // indirect
	github.com/fxamacker/cbor/v2 v2.4.0 // indirect
	github.com/go-asn1-ber/asn1-ber v1.5.4 // indirect
	github.com/go-ldap/ldap/v3 v3.4.4 // indirect
	github.com/golang-jwt/jwt/v4 v4.4.3 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/veraison/go-cose v1.0.0 // indirect
	github.com/x448/float16 v0.8.4 // indirect
	golang.org/x/crypto v0.5.0 // indirect
	golang.org/x/mod v0.7.0 // indirect
	golang.org/x/sync v0.1.0 // indirect
	golang.org/x/sys v0.4.0 // indirect
)

```

**Comment by JeyJeyGao** [comment]
Hi Manas, `building.md` is obsolete. You don't need to run `docker --help`. As long as you can call `notation` command, you can use it directly. Thanks for your issue, we will update the installation guide later.
