### ISSUE TITLE
Add Notation CLI to Winget package manager

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#570]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

This feature request is derived from the Notary v2 roadmap, [Simplify installation experience for Notation CLI]( https://github.com/notaryproject/roadmap/issues/76).

To simplify the Notation CLI installation experience, we need to consider providing a native installation package on Windows, that allows users to install Notation with `winget install notation`. 

### What solution do you propose?

Add Notation Windows package to https://github.com/microsoft/winget-pkgs. See an example https://github.com/microsoft/winget-pkgs/pull/104322/files

### What alternatives have you considered?

None

**Comment by iamsamirzon** [comment]
@yizha1  - Can you move it to another milestone after 1.0.0? Does it not have the same restriction as Hombrew

**Comment by kokamkarsahil** [comment]
Hello! I am willing to volunteer for this issue, as discussed in the meeting here: https://www.youtube.com/live/k6O5ecaoBnA?t=08m12s

Thanks!

**Comment by FeynmanZhou** [comment]
@kokamkarsahil Hi Sahil, 
Sorry, this issue was already completed by another maintainer in https://github.com/microsoft/winget-pkgs/pull/117663.

**Comment by FeynmanZhou** [comment]
This issue can be closed since the implementation is done. We have a doc PR to add the Winget installation to the documentation in https://github.com/notaryproject/notaryproject.dev/pull/338.
