### ISSUE TITLE
Documenting the security process for Notation

### ISSUE THREAD

**Issue by dims** [notaryproject/notation#578]
Can you please draft/adopt an explicit security policy that is written down? I can recommend the one for containerd [1] which is pretty light weight.

I do see that you have a way for users to report [2], but would be good to add details. Apologies if it is already there and i can't find it.

[1] https://github.com/containerd/project/blob/main/SECURITY.md
[2] https://github.com/notaryproject/notation/security/advisories/new

**Comment by dims** [comment]
I see at least one GH advisory here:
https://github.com/notaryproject/notation-go/security/advisories/GHSA-87x9-7grx-m28v

**Comment by toddysm** [comment]
The draft security policy PR is available at https://github.com/notaryproject/.github/pull/5

**Comment by dims** [comment]
thanks @toddysm !

**Comment by dims** [comment]
now that it is up. let me close this.
