### ISSUE TITLE
Release Notation CLI v1.0.0-rc.3

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#582]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

This is for releasing a new version of Notation CLI, which includes
- Change the default signature manifest to using image manifest
- Introduce a new option for users to sign using an on-demand key

### What did you expect to happen?

Release `v1.0.0-rc.3` for `notation CLI`:

- [ ] Decide on main commit for a release
- [ ] Cut branch named `v1.0.0-rc.3` based on agreed upon main commit
- [ ] Cut a tag named `v1.0.0-rc.3`

Please respond with `+1` comment for approval.

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

N/A

**Comment by FeynmanZhou** [comment]
Can we link the detailed commits here to show what has been updated compared to RC.2?

**Comment by yizha1** [comment]
The release will cut on this commit https://github.com/notaryproject/notation/commit/9b714c7e1afbccee966b48cc63ed69af4d3f523c, https://github.com/notaryproject/notation/pull/579

**Comment by priteshbandi** [comment]
+1

**Comment by JeyJeyGao** [comment]
+1

**Comment by vaninrao10** [comment]
+1

**Comment by patrickzheng200** [comment]
+1

**Comment by shizhMSFT** [comment]
+1

**Comment by yizha1** [comment]
The main commit for the release is [233c0ea](https://github.com/notaryproject/notation/commit/233c0ea71edfb68b951eb54a739a101e2a05cd26).
