### ISSUE TITLE
Update references from Notary v2 to Notation

### ISSUE THREAD

**Issue by dims** [notaryproject/notation#586]
- Slack channel and references to slack channel 
- https://cs.github.com/?scopeName=All+repos&scope=&q=notary-v2+org%3Anotaryproject
- https://github.com/search?q=org%3Anotaryproject+%2Fnotary%5B+-%5D%2Bv2%2F&type=code

**Comment by yizha1** [comment]
- [ ] Slack channel and references to slack channel
- [ ] Removing `Notary v2` in `notation` repo was already done.

Removing reference `Notary v2` in other repos were tracked by different tasks:

- https://github.com/notaryproject/notation-go/issues/287
- https://github.com/notaryproject/notation-core-go/issues/127
- https://github.com/notaryproject/notaryproject/issues/244

So, I suggest closing this issue, and focusing on the other issues @dims What do you think?

**Comment by dims** [comment]
@yizha1 sounds good to me!

/close

**Comment by yizha1** [comment]
Closed as agreed.
