### ISSUE TITLE
Login without credential helper

### ISSUE THREAD

**Issue by ningziwen** [notaryproject/notation#587]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

The issue is to track making login work without credential helper. Context: https://github.com/notaryproject/notation/pull/566#issuecomment-1455284235

### What solution do you propose?

Make use of https://github.com/oras-project/oras-credentials-go.

### What alternatives have you considered?

N/A

**Comment by FeynmanZhou** [comment]
This is a good request and duplicates with another one https://github.com/notaryproject/notation/issues/600. I will close #600 . @ningziwen Would you be able to continue work on this issue either?

**Comment by ningziwen** [comment]
@FeynmanZhou Do you mean the current issue #587? I think based on the conversation [here](https://github.com/notaryproject/notation/pull/566#issuecomment-1455284235), this relies on the completion of [credentials-go](https://github.com/oras-project/oras-credentials-go) and we can't do anything for this in notation repo immediately. This issue is only for tracking purpose and we can onbly start working on it when credential-go is completed.

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou Do you mean the current issue #587? I think based on the conversation [here](https://github.com/notaryproject/notation/pull/566#issuecomment-1455284235), this relies on the completion of [credentials-go](https://github.com/oras-project/oras-credentials-go) and we can't do anything for this in notation repo immediately. This issue is only for tracking purpose and we can only start working on it when credential-go is completed.

@ningziwen You are correct. I will inform the status here if ORAS [credentials-go](https://github.com/oras-project/oras-credentials-go) has the first release.

**Comment by yizha1** [comment]
Closed as Notation CLI supports `oras-credentials-go` since v1.0.0-rc.6, see the announcement https://notaryproject.dev/blog/2023/announcing-notation-rc6/
