### ISSUE TITLE
add labels for features subject to changes with proper doc

### ISSUE THREAD

**Issue by qweeah** [notaryproject/notation#596]
Suggest feature labels:

- experimental: features not intended for production usage and may change or be removed in future version.
- preview: feature with known issues or limitations, subject to change but will be included in future releases

Also add documentation for it.

_Originally posted by @yizha1 in https://github.com/notaryproject/notation/issues/593#issuecomment-1480534922_

**Comment by yizha1** [comment]
Closed as experimental feature flag was released in v1.0.0-rc.4, see the announcement https://notaryproject.dev/blog/2023/announcing-notation-rc4/
