### ISSUE TITLE
Simplify Docker Credential Helper configuration for Notation authentication

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#600]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

To achieve maximum compatibility with existing systems, [docker credential helpers](https://github.com/docker/docker-credential-helpers) and its [protocol](https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol) are adopted as the credential helpers for Notation registry authentication.

It requires cumbersome steps to configure [docker credential helpers](https://github.com/docker/docker-credential-helpers) when users log in to a registry. Users will encounter an authentication problem in Linux as follows if the Docker Credential Helper configuration is not configured or misconfigured:

```
Error: could not get the credentials store: failed to load config file, error: credentials store config was not set up
```

We need to simplify the authentication experience and remove dependency on Docker Credential Helper configuration.

### What solution do you propose?

Integrate [oras-credentials-go](https://github.com/oras-project/oras-credentials-go) library to simplify this authentication experience and remove the dependency. This library will be able to read credentials from the Docker configuration file. 

My expectation is that if there is Docker Hub registry credential stored in the Docker configuration file, users will be able to log in to Docker Hub without additional configuration and input username/password. 

### What alternatives have you considered?

No

**Comment by yizha1** [comment]
update milestone to `v1.0.0-rc.6` per discussion in community call on 5/23/2023
