### ISSUE TITLE
Notation delete returns confusing message

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#604]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

I am trying to delete a key from the keystore but after issuing the `notation key delete` command, I see this:
```
~ notation key delete $TEST_KEY_NAME
wabbit-networks.io: unmarked as default
```

This is quite confusing :( Did the key get deleted or just "unmarked as default"? There is no other command that I can use to "remove" the key and this is my intention - the key is expired and not needed anymore.  

### What did you expect to happen?

I expect the key to be removed from the trust store and the message to be clear that the key is removed.

### How can we reproduce it?

Use the command to delete the key

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26

**Comment by FeynmanZhou** [comment]
For `notation key delete`, I think it should have the option to delete the local key from the Trust Store especially when it is invalid or for testing purpose only. Meanwhile, we could refine the error message to avoid confusion when deleting a signing key.

For `notation cert delete`, if you want to delete the certificate from the Trust Store, try `notation cert delete --type ca --store <trust_storeName> (--all | <cert_fileName>)`. The error message should be refined and those two tags should be considered as required options.
