### ISSUE TITLE
Fix the text for notation version

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#605]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

`notation version` returns the following text:
```
Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26
```
"Notary v2" should not be used anywhere in the Notation documentation or help

### What did you expect to happen?

Use the following text:
```
Notation: A tool to sign and verify artifacts according to the Notary Project signature specification.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26

### How can we reproduce it?

Use the command above

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26

**Comment by patrickzheng200** [comment]
We have fixed this issue. It has been merged into Main.

**Comment by yizha1** [comment]
As @patrickzheng200 mentioned, @toddysm We had removed the `Notary v2` in another PR, but the text looks a bit different from yours.

This was current fix ==> `Notation - a tool to sign, store, and verify artifacts. `

Your proposal ==> `Notation: A tool to sign and verify artifacts according to the Notary Project signature specification.`

Is current fix OK for you @toddysm

**Comment by yizha1** [comment]
Reopen it for confirmation.

**Comment by toddysm** [comment]
I am not sure what "store" means in this context. Can one store any artifact? I think we should remove that part

**Comment by patrickzheng200** [comment]
> I am not sure what "store" means in this context. Can one store any artifact? I think we should remove that part

Nope, we do not have "store" in the Main branch, I removed it in my fix PR. @toddysm @yizha1

**Comment by yizha1** [comment]
@toddysm @patrickzheng200 Sorry I copied the wrong message in my previous comment. Here is the one in main branch `Notation - a tool to sign and verify artifacts.`

**Comment by toddysm** [comment]
LGTM

**Comment by yizha1** [comment]
Close this issue as we reached consensus, and the related PR were merged as well.
