### ISSUE TITLE
[Usability Issue] `notation inspect` help is missing

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#610]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

`notation inspect --help` does not provide any help details. Without this it is not clear how the command should be used.

### What did you expect to happen?

Help details that explain how the command should be used.

### How can we reproduce it?

Use `notation inspect --help` command

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26

**Comment by toddysm** [comment]
It seems a weirdness on my setup. We verified that the help shows up for the command so I will close the issue.

**Comment by FeynmanZhou** [comment]
Yes, `notation inspect` has this CLI help info.

```
notation inspect -h
Inspect all signatures associated with the signed artifact.

Example - Inspect signatures on an OCI artifact identified by a digest:
  notation inspect <registry>/<repository>@<digest>

Example - Inspect signatures on an OCI artifact identified by a tag  (Notation will resolve tag to digest):
  notation inspect <registry>/<repository>:<tag>

Example - Inspect signatures on an OCI artifact identified by a digest and output as json:
  notation inspect --output json <registry>/<repository>@<digest>

Usage:
  notation inspect [reference] [flags]

Flags:
  -d, --debug             debug mode
  -h, --help              help for inspect
  -o, --output string     output format, options: 'json', 'text' (default "text")
  -p, --password string   password for registry operations (default to $NOTATION_PASSWORD if not specified)
      --plain-http        registry access via plain HTTP
  -u, --username string   username for registry operations (default to $NOTATION_USERNAME if not specified)
  -v, --verbose           verbose mode
```
