### ISSUE TITLE
Support experimental feature

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#614]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

Experimental features for CLI commands refer to functionality that are not yet part of the base version of a CLI tool but can be accessed by enabling the appropriate options. The purpose of using experimental features is to enable users to try out new functionality or improvements, and to provide feedback for further development or refinement. It can also help identify issues or bugs that may not have been caught during testing. They may not work as expected and are not recommended for use in production or critical systems.

### What solution do you propose?

The proposal is to use environment variable to enable experimental features for Notation CLI. The proposed name is `NOTATION_EXPERIMENTAL`. 

**What is default behavior?**
By default, the experimental features are disabled. The related CLI command flags are not shown to users from Notation CLI help command. 

**How to enable experimental features?**
To enable experimental features, users set `NOTATION_EXPERIMENTAL_CLI` in their environment, for example `export NOTATION_EXPERIMENTAL_CLI=1`. 

**What will happen after experimental features are enabled?**
The CLI flags related to experimental features are shown to users and marked as `[Experimental]` in the description in the help document. 
When using experimental features, the CLI output should warn the users that these are experimental features, like `Caution: This feature is experimental and may not be fully tested or completed and may be deprecated. Report any issues to "https://github/notaryproject/notation` for further improvement."

**How do users know there are experimental features and how to use them?**
The release note or readme.md should give users guidance on how to enable/disable experimental features, other documents are also required to explain to the users on how to use experimental features.

### What alternatives have you considered?

Another alternative is that by default the experimental features are visible to users, but in order to use them, user need to set the corresponding environment variable.

**Comment by qweeah** [comment]
Can we name the env switch to `NOTATION_EXPERIMENTAL`? `CLI` doesn't make much sense since notation is already a CLI.

**Comment by FeynmanZhou** [comment]
I would vote for the approach of showing the experimental features in CLI help by default. Users will need to set the environment variable like `export NOTATION_EXPERIMENTAL=1` to enable those features. It will provide better visibility for early adopters who are interested in trying new but experimental features. I believe it will help us to gather user feedback easier with this approach.

**Comment by iamsamirzon** [comment]
> I would vote for the approach of showing the experimental features in CLI help by default. It provides better visibility for early adopters who are interested in trying new but experimental features. I believe it will help us to gather user feedback easier with this approach.
> 
> Users will be able to use those experimental features unless they set the environment variable like `export NOTATION_EXPERIMENTAL=1` to enable those features.

I suggest we look at the precedent of the other open source tools in this regard before enabling this by default. IMHO, we should keep CLI pristine and not include experimental features by default

**Comment by yizha1** [comment]
@toddysm Any comments from your side?

**Comment by qweeah** [comment]
Proposing below changes on `notation policy` and its subcommands based on comments so far:

- `policy` and its subcommands will be marked as `[Experimental]` in the help doc.
    ```console
   $ notation -h
   ...
     policy      [Experimental] Manage trust policy configuration
   ...
    ```
- If `NOTATION_EXPERIMENTAL` set to `1`, then experimental features are enabled. 
    - A warning of experimental feature will be shown if `notation policy`, `notation policy import` and `notation policy show` were run
    ```console
    $ NOTATION_EXPERIMENTAL=1 notation policy         
    Caution: This feature is experimental and may not be fully tested or completed and may be deprecated. Report any issues to "https://github/notaryproject/notation"
    [Experimental] Manage trust policy configuration for signature verification.
    
    Usage:
      notation policy [command] [flags]
      notation policy [command]
    
    Available Commands:
      import      [Experimental] Import trust policy configuration from a JSON file
      show        [Experimental] Show trust policy configuration
    
    Flags:
      -h, --help   help for policy
    
    Use "notation policy [command] --help" for more information about a command.
    ```
- Otherwise experimental features are disabled. 
    - `notation policy`, `notation policy import` and `notation policy show` will fail with a prompt guide on why it's failing and how to turn on the switch. 
    ```console
    $ notation policy
    Error: notation policy is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
    $ notation policy import foo
    Error: notation policy import is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
    $ notation policy show
    Error: notation policy show is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
    ```

**Comment by yizha1** [comment]
Thanks all for comments. I have updated the original issue description based on your comments.

**Comment by yizha1** [comment]
> Proposing below changes on `notation policy` and its subcommands based on comments so far:
> 
> * `policy` and its subcommands will be marked as `[Experimental]` in the help doc.
>   ```
>   $ notation -h
>   ...
>    policy      [Experimental] Manage trust policy configuration
>   ...
>   ```
> * If `NOTATION_EXPERIMENTAL` set to `1`, then experimental features are enabled.
>   
>   * A warning of experimental feature will be shown if `notation policy`, `notation policy import` and `notation policy show` were run
>   
>   ```
>   $ NOTATION_EXPERIMENTAL=1 notation policy         
>   Caution: This feature is experimental and may not be fully tested or completed and may be deprecated. Report any issues to "https://github/notaryproject/notation"
>   [Experimental] Manage trust policy configuration for signature verification.
>   
>   Usage:
>     notation policy [command] [flags]
>     notation policy [command]
>   
>   Available Commands:
>     import      [Experimental] Import trust policy configuration from a JSON file
>     show        [Experimental] Show trust policy configuration
>   
>   Flags:
>     -h, --help   help for policy
>   
>   Use "notation policy [command] --help" for more information about a command.
>   ```
> * Otherwise experimental features are disabled.
>   
>   * `notation policy`, `notation policy import` and `notation policy show` will fail with a prompt guide on why it's failing and how to turn on the switch.
>   
>   ```
>   $ notation policy
>   Error: notation policy is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
>   $ notation policy import foo
>   Error: notation policy import is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
>   $ notation policy show
>   Error: notation policy show is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment
>   ```

Thanks @qweeah. It looks good. Looking for a better wording for the error message " Error: notation policy is marked as experimental and not enabled by default. To use it, please set NOTATION_EXPERIMENTAL=1 in your environment". But this can be done during PR review.

**Comment by qweeah** [comment]
Had a discussion with @yizha1 and @patrickzheng200 offline and got below conclusion on the UX: When a command or flag is set to experimental and the switch is off, 
  - the command or flag will be hidden from the output of command-line help doc
  - if the flag is used with non-experimental value, e.g. `nontaion sign --signature-manifest image`, the execution should be terminated with error prompt

**Comment by patrickzheng200** [comment]
> * if the flag is used with non-experimental value, e.g. `nontaion sign --signature-manifest image`, the execution should be terminated with error prompt

Thanks @qweeah, to clarify, the `experimental` tag goes with the flag instead of the flag's value right? In other words, 
`When a command or flag is set to experimental and the switch is off`: 

- if the flag is set, e.g. `nontaion sign --signature-manifest xxx`, the execution would always terminate with error prompt.
