### ISSUE TITLE
Reducing the PR approval count to 2

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#616]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

To increase the velocity of the development, we would like to reduce the PR approval count to 2. The justification is the following: with the current count of 3 approvals we have 4 people who need to be involved in the PR. Our initial goal was to have min 3. By reducing to 2 approvals required we still have 3 people including the original submitter.

### What did you expect to happen?

Reduce PR approvals to 2

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

N/A

**Comment by shizhMSFT** [comment]
LGTM

**Comment by yizha1** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
+1. Linking to the PR time cost metrics for this repository in each month: https://ossinsight.io/analyze/notaryproject/notation#pull-requests. 75% PRs take 19 days in Mar, which increased from 16 days in Feb.

![image](https://user-images.githubusercontent.com/40452856/230266402-3a689901-b7bc-4f62-a1ba-6ef1877b558d.png)

**Comment by patrickzheng200** [comment]
LGTM

**Comment by yizha1** [comment]
@priteshbandi  @rgnote, @gokarnm, @vaninrao10 and @iamsamirzon looking for your comments

**Comment by vaninrao10** [comment]
LGTM - but the recent delays is not because of 3 maintainer approvals. Not even 1 maintainer has approved the PR and thats the problem, it is either prioritizing and setting up the expectation. Ex: Local signing and Revocation is the 10 days delay we have seen and the longer delays.

**Comment by rgnote** [comment]
LGTM

**Comment by yizha1** [comment]
We reached consensus with most notation maintainers (4/6). The next step is to enforce the new policy in notation repo

**Comment by shizhMSFT** [comment]
Reduced the required count of PR approvals from 3 to 2.
