### ISSUE TITLE
`notation sign` error messages are not helpful to understand what parameter is missing

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#618]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

The following command `notation sign --signature-format cose --key $REMOTE_KEY_NAME $DEST_IMAGE` returns the following error message: `Error: missing reference`

From that error message is not clear what reference is missing. Actually the error is even more confusing because reference assumes reference to the artifact and the actual error was missing key.

### What did you expect to happen?

Meaningful error like: "Missing key parameter required for signing" or missing "Artifact reference required for signing".

### How can we reproduce it?

Issue the command listed above.

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26

**Comment by yizha1** [comment]
Move to post v1 release, as it is not critical for v1 release. cc @vaninrao10

**Comment by yizha1** [comment]
Fixed by https://github.com/notaryproject/notation/pull/810
