### ISSUE TITLE
Improve the error for missing trust policy

### ISSUE THREAD

**Issue by toddysm** [notaryproject/notation#621]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

The current response is:
```
notation verify $APPLICATION_IMAGE
Warning: Always verify the artifact using digest(@sha256:...) rather than a tag(:kubeconeu-demo-v1) because resolved digest may not point to the same signed artifact, as tags are mutable.
Error: open trustpolicy.json: no such file or directory
```

### What did you expect to happen?

Similar behavior as in #620 

### How can we reproduce it?

Delete the trust policy file and try to verify image

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version: 1.0.0-rc.3
Go version: go1.20.1
Git commit: https://github.com/notaryproject/notation/commit/233c0ea71edfb68b951eb54a739a101e2a05cd26

**Comment by yizha1** [comment]
Need to design what the error message should look like before implementation.

**Comment by yizha1** [comment]
Closed as fixed by PR https://github.com/notaryproject/notation-go/pull/311 in `notation-go`

**Comment by toddysm** [comment]
@yizha1 I do not see the design for the error message. Is this documented somewhere in guidelines how we should handle error messages?

**Comment by yizha1** [comment]
@toddysm Sorry to update the error message for this specific case.

If the trust policy is not created,

The original error message is `Error: open trustpolicy.json: no such file or directory`

The new one is:

`Error: trust policy is not present. To create a trust policy, see: https://notaryproject.dev/docs/quickstart/#create-a-trust-policy`

After this is fixed, the troubleshooting guide will be updated accordingly. The current https://notaryproject.dev/docs/troubleshooting/#when-i-verify-an-artifact-i-get-the-error-error-open-homeconfignotationtrustpolicyjson-no-such-file-or-directory, I will create an issue for it.

Do you mean other document that we need to create for all the error messages for trust policy handling or else?

**Comment by yizha1** [comment]
update milestone to `v1.0.0-rc.6` per discussion in community call on 5/22/2023

**Comment by toddysm** [comment]
Ok, this seems friendlier. Thanks!

**Comment by Two-Hearts** [comment]
Closing this issue as we have reached agreement. (This issue is fixed by PR https://github.com/notaryproject/notation-go/pull/311 in notation-go.)
