### ISSUE TITLE
Flag `--plain-http` didn't explicitly remind users the insecure connection to registries 

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#623]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

The flag `--plain-http` allows notation commands to establish an insecure connection to registries, which is implicit to users. This could be a security risk if users connect to an insecure registry.

This flag exists for the following commands:
- `notation sign`
- `notation verify`
- `notation list`
- `notation inspect`
- `notation login`

### What did you expect to happen?

Update the description of the flag to explicitly inform users that this flag allows insecure connection to registries. for example:

`--plain-http`               Use HTTP protocol while connecting to registries. Use it only for testing purposes.

### How can we reproduce it?

Run `help` command

### Describe your environment

WSL

### What is the version of your Notation CLI or Notation Library?

`v1.0.0-rc.3`

**Comment by patrickzheng200** [comment]
I will take this one.

**Comment by yizha1** [comment]
Thanks @patrickzheng200, I update the expectation section to keep the flag, but update the descriptions

**Comment by yizha1** [comment]
@toddysm do you have any comments on the updated description:

`--plain-http Use HTTP protocol while connecting to registries. Use it only for testing purposes. `

**Comment by toddysm** [comment]
I believe @patrickzheng200 wrote a spec where we completely remove the `--plain-http` flag. Adding too many flags clutters the UX and confuses the users.

@patrickzheng200 please link the spec to this issue.

**Comment by sajayantony** [comment]
This issue currently looks like its about updating the comments, only. 
I think we can retitle this to rename the flag itself to `--insecure` 
One question was to see if we can avoid scope increase to skip TLS verification. 

If we plan to skip tls verification maybe we should consider bundling this under insecure or should we look at skip_tls similar to - https://github.com/containerd/containerd/blob/main/docs/hosts.md#bypass-tls-verification-example

/cc @toddysm should we consider this flag under the trust policy instead?

**Comment by Two-Hearts** [comment]
> I believe @patrickzheng200 wrote a spec where we completely remove the `--plain-http` flag. Adding too many flags clutters the UX and confuses the users.
> 
> @patrickzheng200 please link the spec to this issue.

Hi @toddysm, I don't remember I created a spec related to `--plain-http`, maybe someone else did? 
(btw, this is Patrick, my github account encountered some issue, working on it).

**Comment by yizha1** [comment]
> This issue currently looks like its about updating the comments, only. I think we can use this issues this to rename the flag itself to `--insecure` One question was to see if we can avoid scope increase to skip TLS verification.
> 
> If we plan to skip tls verification maybe we should consider bundling this under insecure or should we look at skip_tls similar to - https://github.com/containerd/containerd/blob/main/docs/hosts.md#bypass-tls-verification-example
> 
> /cc @toddysm should we consider this flag under the trust policy instead? @shizhMSFT added that trust policy won't be feasible since this this path applies to signing and verification. Given that I take back the trust policy option.

Thanks @sajayantony how about changing the name to `--insecure-registry` with description `Use HTTP protocol while connecting to registries. Use it only for testing purposes.`  With this it gives clear indication to the users that it is insecure and used for connecting to registries only. Later if we support "not verify TLS connection", we can update the description accordingly. @shizhMSFT @toddysm @vaninrao10 @priteshbandi @iamsamirzon Any comments?

**Comment by shizhMSFT** [comment]
`--insecure-registry` LGTM

**Comment by iamsamirzon** [comment]
--insecure-registry LGTM

**Comment by sajayantony** [comment]
Related issue - https://github.com/oras-project/oras/discussions/943 would avoid confusing the user with different flags.

**Comment by yizha1** [comment]
The solution is to make `--plain-http` as an alias for flag `--insecure-registry`

`--insecure-registry Use HTTP protocol while connecting to registries. Use it only for testing purposes (alias: --plain-http)`

**Comment by sajayantony** [comment]
LGTM.

**Comment by toddysm** [comment]
Sorry, can somebody remind me why we decided to go with `--insecure-registry` over `--insecure` only? Will be good to document the reasonining in the issue.

**Comment by yizha1** [comment]
@toddysm  This discussion was initiated here https://github.com/notaryproject/notation/issues/623#issuecomment-1539983754, and followed-up by votes.

**Comment by yizha1** [comment]
Since we are going to release a new release candidate, so `--plain-http` is dropped. Use `--insecure-registry` as the flag, and with updated description text.
