### ISSUE TITLE
Introduce an experimental flag to enable backward compatibility with OCI registries

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#630]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

We have a Notation user who recently encountered a problem that not being able to view the signature after signing an artifact stored in Google Artifact Registry.

```
$ notation ls us-west1-docker.pkg.dev/xyz/test/net-monitor:v1
…
failed to decode response: invalid character '<' looking for beginning of value
```

It works well when using `oras discover` with a [compatibility flag](https://github.com/oras-project/oras/blob/main/docs/proposals/compatibility-mode.md#configure-compatibility-with-oci-registry-using-a-flag---distribution-spec) `--distribution-spec`. 

```
$ oras discover us-west1-docker.pkg.dev/xyz/test/net-monitor:v1-o tree --distribution-spec v1.1-referrers-tag

us-west1-docker.pkg.dev/xyz/test/net-monitor@sha256:123456
└── application/vnd.cncf.notary.signature
    └── sha256:123456
```

 

### What solution do you propose?

We may need to introduce an experimental flag like `--compatibility oci-v1.0` to `notation ls` to enable maximum backward compatibility with OCI v1.0 compliant registries, which is similar to ORAS [--distribution-spec](https://github.com/oras-project/oras/blob/main/docs/proposals/compatibility-mode.md#configure-compatibility-with-oci-registry-using-a-flag---distribution-spec). 

It will help Notation users to view the signatures associated with an artifact, regardless of whether the registry complies with the OCI Spec v1.0 or v1.1 or supports Referrers API. 

In a similar case, ORAS uses `--distribution-spec <spec version>-<api>-<option>` to configure the backward compatibility with the registry. I think this format might be complicated for Notation users if we just copy it. 

If you have an idea about the flag name, please comment below. 

### What alternatives have you considered?

/

**Comment by yizha1** [comment]
Closed as it is not applicable now.
