### ISSUE TITLE
Standardize symlink checking per trust store spec

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#634]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

According to [trust store spec](https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-policy.md#trust-store), symlink are not supported

```
Symlinks are not supported for the named store directories or certificate files. 
Implementation MUST validate that the named store directory or certificate files are not symlinks, 
and fail if it does not meet this condition.
``` 

This issue is to ensure the symlink checking is enforced in a standardized way for trust stores.

### What did you expect to happen?

Perform a code review under the following repos to make sure symlink checking is enforced in a standardized way for trust store implementation.

- notation
- notation-go

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

v1.0.0-rc.3

**Comment by priteshbandi** [comment]
Similarly we have this check for plugin https://github.com/notaryproject/notation-go/blob/7987c85e461f726a6da2c96f2c74d5b894fe90ad/plugin/plugin.go#L68-L76
