### ISSUE TITLE
Release Notation CLI v1.0.0-rc.4

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#640]
Release `v1.0.0-rc.4` for `notation`:

- [ ] Update dependency to use `notation-core-go` version `v1.0.0-rc.3`, and `notation-go` version `v1.0.0-rc.4`
- [ ] Decide on main commit for a release
- [ ] Cut branch named `v1.0.0-rc.4` based on agreed upon main commit
- [ ] Cut a tag named `v1.0.0-rc.4`

@priteshbandi @patrickzheng200 @JeyJeyGao @shizhMSFT @vaninrao10 @rgnote @gokarnm @iamsamirzon @toddysm @FeynmanZhou

**Comment by patrickzheng200** [comment]
LGTM

**Comment by yizha1** [comment]
Will create new issue once commit is decided
