### ISSUE TITLE
Release v1.0.0-rc.4 for notation

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#641]
Release `v1.0.0-rc.4` for `notation`:

- [ ] Update dependency to use `notation-core-go` version `v1.0.0-rc.3`, and `notation-go` version `v1.0.0-rc.4`
- [ ] Decide on main commit for a release: 6cd6555 and PR bump up versions
- [ ] Cut branch named `v1.0.0-rc.4` based on agreed upon main commit
- [ ] Cut a tag named `v1.0.0-rc.4`

@priteshbandi @patrickzheng200 @JeyJeyGao @shizhMSFT @vaninrao10 @rgnote @gokarnm @iamsamirzon @toddysm @FeynmanZhou @NiazFK @justincormack @SteveLasker

**Comment by priteshbandi** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by patrickzheng200** [comment]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by yizha1** [comment]
Thanks. We reached majority.

**Comment by FeynmanZhou** [comment]
LGTM

**Comment by yizha1** [comment]
Closed as RC-4 released.
