### ISSUE TITLE
Deprecate --signature-manifest flag from notation sign

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#660]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

`notation sign` has a flag `--signature-manifest` to sign an artifact and store the signature using OCI artifact manifest. This flag is defined in [notation sign](https://github.com/notaryproject/notation/blob/main/specs/commandline/sign.md#experimental-sign-an-artifact-and-store-the-signature-using-oci-artifact-manifest).

[image-spec v1.1.0-rc.3](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc.3) removed OCI artifact manifest. This is a breaking change that we need to rethink when delivering a stable Notation v1.0.0.

### What solution do you propose?

Deprecate `--signature-manifest` flag from `notation sign` but still enable Notation users to read and verify the existing signatures stored with the OCI artifact manifest type in registries that comply with OCI Distribution Spec v1.1.0-RC.1. 
There might be some users who are using previous Notation releases. So Notation should still care for those old artifact manifests (signatures). 

### What alternatives have you considered?

N/A

**Comment by Two-Hearts** [comment]
Thanks @FeynmanZhou, I will take this one.

**Comment by priteshbandi** [comment]
Cross posting my comment https://github.com/notaryproject/notation/issues/659#issuecomment-1541121437
