### ISSUE TITLE
Trace the execution of executables

### ISSUE THREAD

**Issue by Wwwsylvia** [notaryproject/notation#662]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

After migrating to `oras-credentials-go`, we will no longer be able to trace the execution of the external credentials helper like

https://github.com/notaryproject/notation/blob/2e56dd42e385ee1568c5e13e6ef38edb2a549500/pkg/auth/native_store.go#L47

### What solution do you propose?

We still want to trace the execution of native credential helpers when using `oras-credentials-go` to manage credentials. 
This also requires the support from `oras-credentials-go`.
See https://github.com/notaryproject/notation/pull/654#discussion_r1180080763 for the context.

Work item on `oras-credentials-go`: https://github.com/oras-project/oras-credentials-go/issues/63

### What alternatives have you considered?

N/A

**Comment by wangxiaoxuan273** [comment]
I would like to work on this issue.
