### ISSUE TITLE
Low code coverage (33%) reported for notation main branch

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#667]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

The code coverage reported for notation main branch is `33%` https://app.codecov.io/gh/notaryproject/notation, which is low and not good. It indicated that more than 50% of the code was not tested. There are E2E test cases introduced for Notation CLI, I am not sure whether the report covered this part.

### What did you expect to happen?

Improve the code coverage from 33% to at least 75%

### How can we reproduce it?

Code coverage was reported here https://app.codecov.io/gh/notaryproject/notation

### Describe your environment

N/A

### What is the version of your Notation CLI or Notation Library?

Latest main branch

**Comment by qweeah** [comment]
E2E tests coverage are not calculated in the coverage report. Before 1.20,  Golang doesn't support instrumenting a binary to generate code coverage, which is introduced in 1.20, see [collecting code coverage profiles for go programs](https://go.dev/testing/coverage/).

We can utilize this new feature to show merged code coverage of both Notation CLI unit and e2e tests.
