### ISSUE TITLE
E2E test update to align with Notation CLI rc.5 and OCI specs

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/notation#668]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

Notation CLI rc.5 will have the following changes:
1. On signing, removed support of storing signatures as OCI artifact manifest.
2. Moved the Referrers API behind experimental on all commands. By default, the Referrers tag schema is used.

Notation's E2E test data and logic are still using OCI artifact manifest and the Referrers API as default.

### What did you expect to happen?

Once Notation rc.5 is released, the E2E test framework should be updated to align with changes in the release.

### How can we reproduce it?

n/a

### Describe your environment

all enironments

### What is the version of your Notation CLI or Notation Library?

Notation CLI v1.0.0-rc.4

**Comment by yizha1** [comment]
@Two-Hearts  @JeyJeyGao @shizhMSFT Is this issue still valid? Maybe we can consider update it to "E2E test" update for OCI 1.1 support. So I removed `stale` label for now.
