### ISSUE TITLE
Images not accessible in dark theme 

### ISSUE THREAD

**Issue by sajayantony** [notaryproject/notation#67]
The readme has images that aren't visible correctly in dark theme. Here is a screenshot. 

https://github.com/notaryproject/nv2/blob/prototype-2/README.md

![image](https://user-images.githubusercontent.com/1821104/129401810-dbad206b-2cae-4e14-a6c6-ea56bf735a9f.png)

@SteveLasker

**Comment by SteveLasker** [comment]
ack, I’ll update the background in the next round of content updates.

**Comment by sajayantony** [comment]
Fixed by #78
