### ISSUE TITLE
Vote for release of 1.0.0-rc.5 of notation CLI 

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#671]
We need 3 approvals from the current maintainers to vote for tagging[ d850c3f](https://github.com/notaryproject/notation/commit/d850c3f4ef79193ef88f9c6af75cdd8935d1ef18) as `v1.0.0-rc.5`. Here is the link to [change log](https://github.com/notaryproject/notation/compare/v1.0.0-rc.4...d850c3f) and I've also summarized the changes at the end of the issue.

- [ ] Junjie Gao <junjiegao@microsoft.com> (@JeyJeyGao)
- [x] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [ ] Patrick Zheng <patrickzheng@microsoft.com> (@patrickzheng200)
- [x] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [x] Rakesh Gariganti <garigant@amazon.com> (@rgnote)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)
----
### change log for rc5
* https://github.com/notaryproject/notation/pull/650
* https://github.com/notaryproject/notation/pull/651
* https://github.com/notaryproject/notation/pull/666
* https://github.com/notaryproject/notation/pull/663
* https://github.com/notaryproject/notation/pull/665
* https://github.com/notaryproject/notation/pull/656
* https://github.com/notaryproject/notation/pull/658
* https://github.com/notaryproject/notation/pull/670

**Comment by gokarnm** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by priteshbandi** [comment]
Released RC5 https://github.com/notaryproject/notation/releases/tag/v1.0.0-rc.5.
