### ISSUE TITLE
`list` command spec is inconsistent

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation#677]
### What is the areas you experience the issue in?

Notation CLI

### What is not working as expected?

In the [list command spec](https://github.com/notaryproject/notation/blob/main/specs/commandline/list.md)
The output format in description is reference by digest:
```sh
<registry>/<repository>@<digest>
└── application/vnd.cncf.notary.signature
    ├──<digest_of_signature_manifest>
    └──<digest_of_signature_manifest>
```
But in the example, the output is reference by tag:
```sh
localhost:5000/net-monitor:v1
└── application/vnd.cncf.notary.signature
    ├── sha256:647039638efb22a021f59675c9449dd09956c981a44b82c1ff074513c2c9f273
    └── sha256:6bfb3c4fd485d6810f9656ddd4fb603f0c414c5f0b175ef90eeb4090ebd9bfa1
```
Which one is expected? Currently, the code always output the reference by digest.

### What did you expect to happen?

Need to be decided.

### How can we reproduce it?

run `notation list $ref`

### Describe your environment

Linux x64

### What is the version of your Notation CLI or Notation Library?

Notation RC.5

**Comment by FeynmanZhou** [comment]
I think the example output in the CLI spec needs to be updated from tag to digest as follows:

```
localhost:5000/net-monitor@sha256:<digest>
└── application/vnd.cncf.notary.signature
    ├── sha256:647039638efb22a021f59675c9449dd09956c981a44b82c1ff074513c2c9f273
    └── sha256:6bfb3c4fd485d6810f9656ddd4fb603f0c414c5f0b175ef90eeb4090ebd9bfa1
```

This is an inconsistency doc issue.
