### ISSUE TITLE
docs: `notation login` error message improvement

### ISSUE THREAD

**Issue by Wwwsylvia** [notaryproject/notation#681]
### What is the areas you would like to add the new feature to?

Notation CLI

### Is your feature request related to a problem?

When we run `notation login` with a valid username and password, and there is no credentials store configured, we get the below error message:

![image](https://github.com/notaryproject/notation/assets/8113721/09c6afa0-f99e-4e9a-b8d0-04ce773c9f4e)

> failed to log in to {registryName}, the credential could not be saved because a credentials store is required to securely store the password. See https://notaryproject.dev/docs/how-to/registry-authentication/

The error message is thrown from [here](https://github.com/notaryproject/notation/blob/main/cmd/notation/login.go#L126-L127).

There is a chance that we have another valid credential stored in docker config file, and we can do `notation sign` successfully, although the login command failed.
Is there any way to improve the error message to convey this information to users and avoid confusions?

### What solution do you propose?

For the case where there is an existing credential that does not match the provided valid credential, @Two-Hearts proposed the below error message in the [PR comment](https://github.com/notaryproject/notation/pull/654#discussion_r1201510820):

> failed to log in to {registryName}: user provided credential does not match the existing one.  To log in, a credentials store is required to securely store the new password. See https://notaryproject.dev/docs/how-to/registry-authentication/.

### What alternatives have you considered?

Still thinking

**Comment by FeynmanZhou** [comment]
This URL https://notaryproject.dev/docs/how-to/registry-authentication/ is also broken in v1.0.1. IMO, the minimum fix of this issue in v1.1.0 is to update the broken link to https://notaryproject.dev/docs/user-guides/how-to/registry-authentication/.

**Comment by Wwwsylvia** [comment]
Just revisited this issue and now I don't think we really need it.

The initial concern was related to a scenario where a user logs in with the correct credentials using `notation login`, but no credential store is available to save the password. Additionally, there could be different credentials stored in plaintext by another application.

In such cases, should we send an additional request to the registry to verify if the existing credentials are valid? If they are valid, should we inform the user about the existing credentials?

I think this is unnecessary. If the user is using new credentials with `notation login`, it implies they don't care about the old ones. We should avoid over-complicating the design unless users explicitly raise this as an issue.
