### ISSUE TITLE
Vote for release of notation v1.0.0-rc.6

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#686]
We need `4` approvals from the current `6` maintainers to vote for tagging [cc3f7aa](https://github.com/notaryproject/notation/commit/cc3f7aa06b600a689af5274daa7c06fb3e55e69e) as `v1.0.0-rc.6`. Here is the link to [change log](https://github.com/notaryproject/notation/compare/v1.0.0-rc.5...cc3f7aa06b600a689af5274daa7c06fb3e55e69e) .

- [x] Junjie Gao <junjiegao@microsoft.com> (@JeyJeyGao)
- [x] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [x] Patrick Zheng <patrickzheng@microsoft.com> (@Two-Hearts)
- [x] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [x] Rakesh Gariganti <garigant@amazon.com> (@rgnote)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)

----
### change log for v1.0.0-rc6
* doc: add link to README to docs for clarity by @zr-msft in https://github.com/notaryproject/notation/pull/636
* doc: improve error output in notation key and notation cert by @FeynmanZhou in https://github.com/notaryproject/notation/pull/606
* test: generate e2e coverage profile by @qweeah in https://github.com/notaryproject/notation/pull/669
* doc: update building guide by @JeyJeyGao in https://github.com/notaryproject/notation/pull/563
* fix: fixed global variable verifier by @Two-Hearts in https://github.com/notaryproject/notation/pull/676
* update: renamed flag --plain-http to --insecure-registry by @Two-Hearts in https://github.com/notaryproject/notation/pull/674
* chore: update account info for Patrick Zheng by @yizha1 in https://github.com/notaryproject/notation/pull/672
* build(deps): Bump github.com/sirupsen/logrus from 1.9.0 to 1.9.2 by @dependabot in https://github.com/notaryproject/notation/pull/678
* refactor: use `oras-credentials-go` for credential management by @Wwwsylvia in https://github.com/notaryproject/notation/pull/654
* chore: updated warning printout logic for Sign with --allow-referrers-api flag by @Two-Hearts in https://github.com/notaryproject/notation/pull/682
* test: add e2e test cases for flag `--insecure-registry` by @JeyJeyGao in https://github.com/notaryproject/notation/pull/679
* update: based on spec, updated messages of notation key command by @Two-Hearts in https://github.com/notaryproject/notation/pull/684
* fix: added digest check on resolve ref by @Two-Hearts in https://github.com/notaryproject/notation/pull/689
* build: bump up versions and dependencies by @priteshbandi in https://github.com/notaryproject/notation/pull/685

**Comment by yizha1** [comment]
LGTM but IANAM

**Comment by Two-Hearts** [comment]
LGTM

**Comment by JeyJeyGao** [comment]
LGTM

**Comment by FeynmanZhou** [comment]
Support +1

**Comment by shizhMSFT** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by shizhMSFT** [comment]
The build for cc3f7aa was failed.

**Comment by shizhMSFT** [comment]
The E2E test has been fixed by #690. Since the fix only applies to the e2e test, we can continue to release `v1.0.0-rc.6`.

**Comment by gokarnm** [comment]
LGTM
