### ISSUE TITLE
Vote for release of notation v1.0.0-rc.7

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#694]
We need `4` approvals from the current `6` maintainers to vote for tagging [ebfb9ef](https://github.com/notaryproject/notation/commit/ebfb9ef707996e1dc11898db8b90faa8e8816ae6) as `v1.0.0-rc.7`. Here is the link to [change log](https://github.com/notaryproject/notation/compare/v1.0.0-rc.6...ebfb9ef707996e1dc11898db8b90faa8e8816ae6) .

- [ ] Junjie Gao <junjiegao@microsoft.com> (@JeyJeyGao)
- [x] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [x] Patrick Zheng <patrickzheng@microsoft.com> (@Two-Hearts)
- [x] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [x] Rakesh Gariganti <garigant@amazon.com> (@rgnote)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)

----
### change log for v1.0.0-rc7
* fix: fixed e2e test after dependency bump up by @Two-Hearts in https://github.com/notaryproject/notation/pull/690
* build: bump version to rc.7 by @yizha1 in https://github.com/notaryproject/notation/pull/691

---
Reason for rc7
we have a failing e2e test in rc6 and for good hygiene we are proposing rc7

**Comment by shizhMSFT** [comment]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by priteshbandi** [comment]
We have 4 out of 6 maintainers approval, going ahead we the release process

**Comment by Two-Hearts** [comment]
LGTM

**Comment by priteshbandi** [comment]
Completed the release https://github.com/notaryproject/notation/releases/tag/v1.0.0-rc.7
