### ISSUE TITLE
Create release builds

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#71]
Start autmoation of building binaries for notation as the next iteration commits to main.

**Comment by sajayantony** [comment]
@shizhMSFT - As part of the release workflow can we rename the CLI - https://github.com/theupdateframework/notary/pull/1609/files#diff-59891d08e1d3e26bb7f23f03f9403d62f279d044266fadba8ffb4cf8515031feR11

**Comment by shizhMSFT** [comment]
Notation CLI Alpha has been proposed.
- #83 

Release builds are currently available under my repo: https://github.com/shizhMSFT/notation/releases/.

**Comment by shizhMSFT** [comment]
Covered by #83 and #135.
