### ISSUE TITLE
Add --force to notation key add

### ISSUE THREAD

**Issue by duffney** [notaryproject/notation#728]
### Is your feature request related to a problem?

Updating an existing key requires that you remove the key and then readd it, to improve the developer experience a `--force` flag should be added to allow the user to overwrite the existing key without having to first remove it.

### What solution do you propose?

Add a `--force` flag to the notation key subcommand.

### What alternatives have you considered?

Removing the key and readding works but it's an extra step that the `--force` flag would resolve.

**Comment by FeynmanZhou** [comment]
[notation key add](https://github.com/notaryproject/notation/blob/main/specs/commandline/key.md#notation-key-add) only adds the key to the Notation signing key list. If you want to update the key in the Notation signing key list, [notation key update](https://github.com/notaryproject/notation/blob/main/specs/commandline/key.md#notation-key-update) might help.

I am curious if overwriting the key and its source key file is a secure operation.

**Comment by duffney** [comment]
I should have dug into the other available subcommands first. :) Having the update subcommand takes care of my issue Closing issue, thank you for the reply @FeynmanZhou.
