### ISSUE TITLE
Update github actions version comments

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation#747]
### What is not working as expected?

The version coment stypes are not consistent.
https://github.com/notaryproject/notation/blob/0cc39b31b92b86150590b208a3caafbf1e09ac09/.github/workflows/scorecard.yml#L41-L64

Also the license checker is not pinned commit.
https://github.com/notaryproject/notation/blob/0cc39b31b92b86150590b208a3caafbf1e09ac09/.github/workflows/license-checker.yml#L26C1-L28C38

### What did you expect to happen?

We should update the version comment to use the same stype like `v.*` 
Also update `license-checker.yml` to use pinned commit version comment after `notation-core-go` releases new version.

### How can we reproduce it?

See the file in the repo.

### Describe your environment

Github repo.

### What is the version of your Notation CLI or Notation Library?

Notation v1.0.0-rc.7

**Comment by yizha1** [comment]
Closed as completed by https://github.com/notaryproject/notation/pull/742
