### ISSUE TITLE
Release Notation v1.0.0

### ISSUE THREAD

**Issue by shizhMSFT** [notaryproject/notation#749]
According to the [community meeting](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#July-20-2023) on July 20, 2023, we are about to release Notation suite version `v1.0.0`. Here's the check list:

- [x] https://github.com/notaryproject/notation/pull/748
  - [x] https://github.com/notaryproject/notation-go/issues/341
    - [x] https://github.com/notaryproject/notation-core-go/issues/157
    - [x] https://github.com/notaryproject/notation-go/pull/342
  - [x] #752
  - [x] #754
  - Subset of https://github.com/notaryproject/.github/issues/35
    - [x] https://github.com/notaryproject/.github/issues/38
    - [x] https://github.com/notaryproject/.github/pull/32
    - [x] https://github.com/notaryproject/specifications/issues/261
      - [x] https://github.com/notaryproject/specifications/issues/273
    - [x] https://github.com/notaryproject/specifications/pull/256
    - [x] https://github.com/notaryproject/specifications/pull/262
    - [x] https://github.com/notaryproject/specifications/pull/263
    - [x] https://github.com/notaryproject/notation/pull/750
    - [x] https://github.com/notaryproject/notaryproject.dev/pull/328

**Comment by priteshbandi** [comment]
As discussed in 07/24, we are goof for releasing notation-core-go and notation-go but will block notation cli release on notary rebranding issue (https://github.com/notaryproject/.github/issues/35)

**Comment by yizha1** [comment]
How about [e2e testing dependencies](https://github.com/notaryproject/notation/blob/main/test/e2e/go.mod)?

**Comment by shizhMSFT** [comment]
> How about [e2e testing dependencies](https://github.com/notaryproject/notation/blob/main/test/e2e/go.mod)?

They are updated by #754

**Comment by shizhMSFT** [comment]
Closing as [v1.0.0](https://github.com/notaryproject/notation/releases/tag/v1.0.0) has been released.
