### ISSUE TITLE
Use columns with labels for cert list output

### ISSUE THREAD

**Issue by sozercan** [notaryproject/notation#772]
### Is your feature request related to a problem?

If a user is not familiar with trust policy and cert list, they might be confused with the `notation cert list` output

```
$ notation cert list  
/home/sozercan/.config/notation/truststore/x509/ca/wabbit/wabbit-networks.io.crt
/home/sozercan/.config/notation/truststore/x509/ca/wabbit-networks.io/wabbit-networks.io.crt
```

It is not very clear that names of trust stores should be `wabbit` and `wabbit-networks.io` in this case

### What solution do you propose?

It would be clearer to use columns that match the terms and expectations

Suggestion
```
$ notation cert list  
TRUST STORE              CERT PATH
wabbit                  /home/sozercan/.config/notation/truststore/x509/ca/wabbit/wabbit-networks.io.crt
wabbit-networks         /home/sozercan/.config/notation/truststore/x509/ca/wabbit-networks.io/wabbit-networks.io.crt
```

and anything else that might be helpful

### What alternatives have you considered?

n/a

**Comment by yizha1** [comment]
duplicated with issue https://github.com/notaryproject/notation/issues/609
