### ISSUE TITLE
Plan for Notation v1.0.1 patch release

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#804]
This is the proposal of releasing Notation `v1.0.1` patch release, including `notation`, `notation-go` and `notation-core-go`.

Target date: 10/30/2023

Scope:

- Bugs:
  - https://github.com/notaryproject/notation/issues/801
  - https://github.com/notaryproject/notation/issues/773
- Improved error message for configuring unnecessary key usage
  - https://github.com/notaryproject/notation-core-go/issues/164
- Dependency updates

Please propose any other bugs that need to be included in the patch release.

**Comment by FeynmanZhou** [comment]
Notation v1.0.1 was released. Shall we close this issue as completed?

**Comment by yizha1** [comment]
Closed as Notation v1.0.1 was released.
