### ISSUE TITLE
 Provide environmental variables to set the directory of Notation configuration files and plugin binary

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notation#822]
### Is your feature request related to a problem?

There were two environmental variables `NOTATION_LIBEXEC` and `NOTATION_CONFIG` in Notation RC releases that can help users define the directory of Notation configuration files and plugin binaries respectively and pass the values to Notation in advance. See [Notation directory structure for system configuration](https://github.com/notaryproject/notation/blob/v0.11.0-alpha.4/specs/directory.md) for the context. These two environmental variables were removed in RC release. 

After revisiting the setup experience of notation signing and verification, it looks still useful if users want to use Notation in different OS. With these two environmental variables, users can easily define tell Notation where are the directory of Notation plugin binaries, trust policy, and key/cert files in advance. It will simplify signing and verification setup experience without manually retrieving those directory location from different operating system.

### What solution do you propose?

Bring two environmental variables `NOTATION_LIBEXEC` and `NOTATION_CONFIG` back to Notation. Enable users to set the directory of Notation binaries and configuration files respectively by using these two environmental variables.

### What alternatives have you considered?

NA

**Comment by priteshbandi** [comment]
What's the necessity for this? Can't the user utilize XDG_CONFIG_HOME on windows and mac?

**Comment by JeyJeyGao** [comment]
@priteshbandi XDG_CONFIG_HOME is applicable only for Linux. It doesn't work for Windows and macOS. Additionally, by adding NOTATION_CONFIG and NOTATION_LIBEXE, we can simplify the containerized workflows.

**Comment by priteshbandi** [comment]
Can user use `%AppData%` ? Also, why do we need two different variable NOTATION_LIBEXEC and NOTATION_CONFIG; can we use one variable like NOTATION_CONFIG_HOME ?

**Comment by JeyJeyGao** [comment]
Yes, users can utilize %AppData% on Windows, but it is challenging for macOS users. Additionally, the method to change the directory is inconsistent across different operating systems, so providing a consistent way to do it can improve the user experience. I think NOTATION_CONFIG_HOME is suitable for the current status. However, I recall that we had a system-level directory design before: https://github.com/notaryproject/notation/blob/v1.0.0-rc.1/specs/directory.md#system-level

If we are still considering a system-level directory in the future, we might need two different variables for configuration and plugins.

@priteshbandi @FeynmanZhou @shizhMSFT How do you think? If we don't plan to have a system directory, I think only NOTATION_CONFIG_HOME is enough.

**Comment by shizhMSFT** [comment]
`NOTATION_LIBEXEC` and `NOTATION_CONFIG` can direct to very different locations and cannot be covered by one `NOTATION_CONFIG_HOME`.

Consider that a user tries to containerize `notation` with AWS Signer, AKV Signer, etc., plugins packed in. At the runtime, the user may mount the host filesystem to `NOTATION_CONFIG` but that user still want to keep `NOTATION_LIBEXEC` unchanged and still points to those packed plugins.
