### ISSUE TITLE
Killercoda notation demo broken links

### ISSUE THREAD

**Issue by Quanalogy** [notaryproject/notation#885]
### What is not working as expected?

In the end of [the killercoda demo](https://killercoda.com/notaryproject/scenario/notation) you link to https://notationproject.dev/docs/ which is not found. 

### What did you expect to happen?

Go to the documentation page, which I guess should be https://notaryproject.dev/docs/ instead.

### How can we reproduce it?

Go through [the killercoda demo](https://killercoda.com/notaryproject/scenario/notation). At completion you write to look for more in the docs which is a broken link.

### Describe your environment

killercoda.

### What is the version of your Notation CLI or Notation Library?

1.1.0

**Comment by FeynmanZhou** [comment]
Thanks @Quanalogy . There is a mistaken link on the Killercoda site. We will fix it later.
