### ISSUE TITLE
[Local Key Signing] Support signing certificate and certificate chain in Configuration file

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#89]
* Along with signingKey(private key) we will need signing certificate and certificate chain as signing certificate and certchain will be embedded in signature envelope.
* Also, how about using `default` name for default identity? Although this works better with INI format.

```
"signing-identites": [
  {
      "name": "default",
      "signing-certificate": "~/./notary/keys/wabbit-networks.crt",
      "signing-certificate-chain": ""~/./notary/keys/wabbit-networks-chain.crt",
      "private-key": "~/./notary/keys/wabbit-networks.key"
  },
  {
      "name": "import-acme-rockets",
      "signing-certificate": "~/./notary/keys/import-acme-rockets.crt",
      "signing-certificate-chain": ""~/./notary/keys/import-acme-rockets-chain.crt",
      "private-key": "~/./notary/keys/import-acme-rockets.key"
  }
]
```

_Originally posted by @priteshbandi in https://github.com/notaryproject/notation/pull/76#discussion_r700565207_

**Comment by dtzar** [comment]
@priteshbandi - what's the status of this being implemented?

**Comment by priteshbandi** [comment]
Tracking it in https://github.com/notaryproject/roadmap/issues/31
