### ISSUE TITLE
Could you add Arm 32 in official release artefacts?

### ISSUE THREAD

**Issue by lmussier** [notaryproject/notation#943]
### Is your feature request related to a problem?

I would like to use notation on arm32 processors.

### What solution do you propose?

I'd like to see arm in the official releases

### What alternatives have you considered?

Build notation on my own

**Comment by lmussier** [comment]
More or less the same request as this one https://github.com/oras-project/oras/issues/364 :)

**Comment by yizha1** [comment]
@lmussier Are you interested in contributing to fix this issue?

**Comment by lmussier** [comment]
Short answer, yes.
I can make it compile (already done in fact) but I was not able to run tests.

**Comment by yizha1** [comment]
I appreciate your interest @lmussier. You can start working on it and the Notation maintainers will assist you if you encounter any issues. Feel free to ask your questions here. /cc: @notaryproject/notaryproject-notation-maintainers

**Comment by lmussier** [comment]
The easiest is done in #956 
Unit tests (make test) are ok, but I encounter some weird issues with e2e tests, they won't pass on a the current master head.

**Comment by yizha1** [comment]
@lmussier If your PR passes verification and merged, it should be fine. Your log indicated some throttling issues from Docker hub
