### ISSUE TITLE
Proposal for Notation patch release

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#947]
Here is the proposal for Notation patch release including `notation-core-go v1.0.3`, `notation-go v1.1.1` and `notation v1.1.1`. 

**Target date:** 

May 31 2024 (Code freeze on May 24, and release process will start on May 27)

**Scope:**
- Dependencies updates
- Bug fixes
- Error message improvements
  - https://github.com/notaryproject/notation/pull/933
  - https://github.com/notaryproject/notation/pull/834
  - https://github.com/notaryproject/notation-go/issues/404

**Comment by FeynmanZhou** [comment]
OCI Spec v1.1 support https://github.com/notaryproject/notation/pull/916 has been merged into `main` last month. Should we consider this enhancement as a part of v1.1.1?

**Comment by yizha1** [comment]
Here is the updated plan for patch release and I would like to propose additional `notation v1.2.0-alpha.1` release for OCI 1.1 support.

### Releases before end of May 2024
Release driver: @Two-Hearts and @yizha1 
> Require @priteshbandi support on reviewing and approving release PRs next week.

#### `notation-core-go v1.0.3`
#### `notation-go v1.1.1`
Release process:
  1. Check out `release-1.1` based on `main`
  1. On `release-1.1`, revert PR `#379`
  1. Release `v1.1.1` on `release-1.1` branch

Alternatively,
1. Check out `release-1.1` based on `v1.1.0`
2. Cherry pick or backport non-feature commits from main to release-1.1
3. Release `v1.1.1` on `release-1.1` branch

#### `notation v1.1.1`
Release process:
1. Bump up notation-go to `v1.1.1` on `main`
2. Check out `release-1.1` based on `v1.1.0`
3. Cherry pick or backport non-feature commits from `main` to `release-1.1`
4. Release `v1.1.1` on `release-1.1` branch

#### `notation v1.2.0-alpha.1` - With OCI 1.1
Release process:
1. Bump up `notation-go` to the lastest commit on `main` branch
2. Release `v1.2.0-alpha.1` based on `main` branch

### Milestones to `notation v1.2.0` stable release

- `notation v1.2.0-beta.1` / `notation v1.2.0-beta.2` with Blob Sign, Timestamping
- `notation v1.2.0-rc.1` - General testing
- `notation v1.2.0` - Stable version


Tag for comments: @notaryproject/notaryproject-org-maintainers @vaninrao10 @priteshbandi @FeynmanZhou @JeyJeyGao

**Comment by FeynmanZhou** [comment]
LGTM. I will create a new branch for Notation v1.2.0 in the website repository soon.

**Comment by Two-Hearts** [comment]
Closing as the releases have been completed.
