### ISSUE TITLE
Notation commands to default to --plain-http for localhost

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#95]
Similar to the docker cli, it would help getting started docs to have localhost be assumed to be `--plain-http`
Today, I either need to pass `--plain-http` to each command or add it to the insecure registries collection in the config.
```json
"insecureRegistries": [
		"registry.wabbit-networks.io",
		"localhost:5000"
	]
```

## Current Behavior
```bash
notation list localhost:5000/net-monitor:v1
https://localhost:5000/v2/net-monitor/manifests/v1: tls: first record does not look like a TLS handshake
```
To get the above to work:
```bash
notation list --plain-http localhost:5000/net-monitor:v1
sha256:04420c647483531c0e57e89a0ab99ec9f5480a6abc8aff77b5ab8e0880676af6
```

## Expected Behavior

*Without* creating a `insecureRegistries` entry in the config:
```bash
notation list localhost:5000/net-monitor:v1
sha256:04420c647483531c0e57e89a0ab99ec9f5480a6abc8aff77b5ab8e0880676af6
```

**Comment by SteveLasker** [comment]
@shizhMSFT, will this become unified with the oras-go refactoring work?

**Comment by shizhMSFT** [comment]
@SteveLasker Yes, all registry related work will be done after the `oras-go` refactoring work.

**Comment by SteveLasker** [comment]
Ok, great. Lets leave this issue here to track for completion. 
I've updated the labels to reflect a new dependency label.
