### ISSUE TITLE
mark 1.1.1 as latest release

### ISSUE THREAD

**Issue by chenrui333** [notaryproject/notation#968]
### What is not working as expected?

1.1.1 is just a tag atm, not a release

relates to https://github.com/Homebrew/homebrew-core/pull/174400

**Comment by shizhMSFT** [comment]
@chenrui333 We are working on the release draft of `v1.1.1` and it will be released in a few hours.

**Comment by shizhMSFT** [comment]
@chenrui333 [v1.1.1](https://github.com/notaryproject/notation/releases/tag/v1.1.1) was just released!

**Comment by chenrui333** [comment]
thanks!
