### ISSUE TITLE
Notation config should maintain tabs or spaces

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#97]
The notation/config.json file currently uses tabs vs. spaces. While I think believe we should default to 2 spaces, this issue is more about maintaining what the user edits.

If I convert the file to spaces, but then call `notation cert add`, I don't really expect the file to be changed. 
Curious about opening up pandoras box on tabs vs. spaces, but just adding som UX style issues.

**Comment by shizhMSFT** [comment]
Currently, the indention is 4 spaces.
See https://github.com/notaryproject/notation/blob/main/pkg/config/config.go#L47

**Comment by SteveLasker** [comment]
closing for focus as the config may be replaced with the policy work
