### ISSUE TITLE
Notation inspect command timestamp signature support

### ISSUE THREAD

**Issue by JeyJeyGao** [notaryproject/notation#997]
### Is your feature request related to a problem?

![image](https://github.com/user-attachments/assets/15be01bc-e671-41b5-b215-50168467c711)
The timestamp signature field is base64 encoded; however, it is not readable.

### What solution do you propose?

For the notation inspect command, we need to provide readable content for humans. Therefore, for the timestamp signature, we may need to show the actual timestamp, issuer, and the content of the timestamping certificate chain.

### What alternatives have you considered?

No

### Any additional context?

No

**Comment by Two-Hearts** [comment]
A valid issue. Should fix before next release.

**Comment by Two-Hearts** [comment]
`the content of the timestamping certificate chain` this part is not showable, because we can only get the tsa cert chain during timestamp verification where the user must provide the TSA root cert.
